// Word pairs for Undercover game
// Each pair has: civ (civilian word), und (undercover word), cat (category)
// British English throughout

const wordPairs = [
  // ============================================
  // FOOD & DRINK (120 pairs)
  // ============================================
  { civ: "Apple", und: "Pear", cat: "Food & Drink" },
  { civ: "Coffee", und: "Tea", cat: "Food & Drink" },
  { civ: "Pizza", und: "Burger", cat: "Food & Drink" },
  { civ: "Burger", und: "Hot Dog", cat: "Food & Drink" },
  { civ: "Fizzy Drink", und: "Juice", cat: "Food & Drink" },
  { civ: "Cake", und: "Pie", cat: "Food & Drink" },
  { civ: "Ice Cream", und: "Frozen Yoghurt", cat: "Food & Drink" },
  { civ: "Sushi", und: "Sashimi", cat: "Food & Drink" },
  { civ: "Breakfast", und: "Brunch", cat: "Food & Drink" },
  { civ: "Bread", und: "Toast", cat: "Food & Drink" },
  { civ: "Butter", und: "Margarine", cat: "Food & Drink" },
  { civ: "Milk", und: "Cream", cat: "Food & Drink" },
  { civ: "Cheese", und: "Butter", cat: "Food & Drink" },
  { civ: "Yoghurt", und: "Custard", cat: "Food & Drink" },
  { civ: "Biscuit", und: "Cracker", cat: "Food & Drink" },
  { civ: "Crisps", und: "Popcorn", cat: "Food & Drink" },
  { civ: "Chocolate", und: "Caramel", cat: "Food & Drink" },
  { civ: "Honey", und: "Syrup", cat: "Food & Drink" },
  { civ: "Sugar", und: "Salt", cat: "Food & Drink" },
  { civ: "Pepper", und: "Paprika", cat: "Food & Drink" },
  { civ: "Ketchup", und: "Mustard", cat: "Food & Drink" },
  { civ: "Mayonnaise", und: "Aioli", cat: "Food & Drink" },
  { civ: "Vinegar", und: "Lemon Juice", cat: "Food & Drink" },
  { civ: "Olive Oil", und: "Vegetable Oil", cat: "Food & Drink" },
  { civ: "Rice", und: "Pasta", cat: "Food & Drink" },
  { civ: "Noodles", und: "Spaghetti", cat: "Food & Drink" },
  { civ: "Soup", und: "Stew", cat: "Food & Drink" },
  { civ: "Salad", und: "Coleslaw", cat: "Food & Drink" },
  { civ: "Sandwich", und: "Wrap", cat: "Food & Drink" },
  { civ: "Croissant", und: "Danish Pastry", cat: "Food & Drink" },
  { civ: "Muffin", und: "Cupcake", cat: "Food & Drink" },
  { civ: "Doughnut", und: "Bagel", cat: "Food & Drink" },
  { civ: "Pancake", und: "Waffle", cat: "Food & Drink" },
  { civ: "Omelette", und: "Scrambled Eggs", cat: "Food & Drink" },
  { civ: "Bacon", und: "Sausage", cat: "Food & Drink" },
  { civ: "Ham", und: "Turkey", cat: "Food & Drink" },
  { civ: "Chicken", und: "Duck", cat: "Food & Drink" },
  { civ: "Beef", und: "Lamb", cat: "Food & Drink" },
  { civ: "Pork", und: "Veal", cat: "Food & Drink" },
  { civ: "Steak", und: "Roast", cat: "Food & Drink" },
  { civ: "Fish", und: "Prawns", cat: "Food & Drink" },
  { civ: "Salmon", und: "Tuna", cat: "Food & Drink" },
  { civ: "Cod", und: "Haddock", cat: "Food & Drink" },
  { civ: "Lobster", und: "Crab", cat: "Food & Drink" },
  { civ: "Oyster", und: "Mussel", cat: "Food & Drink" },
  { civ: "Banana", und: "Plantain", cat: "Food & Drink" },
  { civ: "Orange", und: "Tangerine", cat: "Food & Drink" },
  { civ: "Lemon", und: "Lime", cat: "Food & Drink" },
  { civ: "Grape", und: "Raisin", cat: "Food & Drink" },
  { civ: "Strawberry", und: "Raspberry", cat: "Food & Drink" },
  { civ: "Blueberry", und: "Blackberry", cat: "Food & Drink" },
  { civ: "Cherry", und: "Plum", cat: "Food & Drink" },
  { civ: "Peach", und: "Nectarine", cat: "Food & Drink" },
  { civ: "Mango", und: "Papaya", cat: "Food & Drink" },
  { civ: "Pineapple", und: "Coconut", cat: "Food & Drink" },
  { civ: "Watermelon", und: "Honeydew", cat: "Food & Drink" },
  { civ: "Cantaloupe", und: "Rockmelon", cat: "Food & Drink" },
  { civ: "Avocado", und: "Guacamole", cat: "Food & Drink" },
  { civ: "Tomato", und: "Pepper", cat: "Food & Drink" },
  { civ: "Cucumber", und: "Courgette", cat: "Food & Drink" },
  { civ: "Carrot", und: "Parsnip", cat: "Food & Drink" },
  { civ: "Potato", und: "Sweet Potato", cat: "Food & Drink" },
  { civ: "Onion", und: "Shallot", cat: "Food & Drink" },
  { civ: "Garlic", und: "Ginger", cat: "Food & Drink" },
  { civ: "Broccoli", und: "Cauliflower", cat: "Food & Drink" },
  { civ: "Cabbage", und: "Lettuce", cat: "Food & Drink" },
  { civ: "Spinach", und: "Kale", cat: "Food & Drink" },
  { civ: "Celery", und: "Asparagus", cat: "Food & Drink" },
  { civ: "Mushroom", und: "Truffle", cat: "Food & Drink" },
  { civ: "Aubergine", und: "Courgette", cat: "Food & Drink" },
  { civ: "Peas", und: "Beans", cat: "Food & Drink" },
  { civ: "Sweetcorn", und: "Peas", cat: "Food & Drink" },
  { civ: "Lentils", und: "Chickpeas", cat: "Food & Drink" },
  { civ: "Tofu", und: "Tempeh", cat: "Food & Drink" },
  { civ: "Hummus", und: "Baba Ganoush", cat: "Food & Drink" },
  { civ: "Peanut Butter", und: "Almond Butter", cat: "Food & Drink" },
  { civ: "Jam", und: "Marmalade", cat: "Food & Drink" },
  { civ: "Jelly", und: "Mousse", cat: "Food & Drink" },
  { civ: "Pudding", und: "Custard", cat: "Food & Drink" },
  { civ: "Trifle", und: "Tiramisu", cat: "Food & Drink" },
  { civ: "Brownie", und: "Flapjack", cat: "Food & Drink" },
  { civ: "Scone", und: "Crumpet", cat: "Food & Drink" },
  { civ: "Cheesecake", und: "Gateau", cat: "Food & Drink" },
  { civ: "Tart", und: "Quiche", cat: "Food & Drink" },
  { civ: "Pastry", und: "Puff Pastry", cat: "Food & Drink" },
  { civ: "Curry", und: "Stir Fry", cat: "Food & Drink" },
  { civ: "Tacos", und: "Burritos", cat: "Food & Drink" },
  { civ: "Nachos", und: "Quesadilla", cat: "Food & Drink" },
  { civ: "Dim Sum", und: "Spring Rolls", cat: "Food & Drink" },
  { civ: "Ramen", und: "Pho", cat: "Food & Drink" },
  { civ: "Pad Thai", und: "Chow Mein", cat: "Food & Drink" },
  { civ: "Falafel", und: "Samosa", cat: "Food & Drink" },
  { civ: "Kebab", und: "Shawarma", cat: "Food & Drink" },
  { civ: "Paella", und: "Risotto", cat: "Food & Drink" },
  { civ: "Lasagne", und: "Moussaka", cat: "Food & Drink" },
  { civ: "Carbonara", und: "Bolognese", cat: "Food & Drink" },
  { civ: "Gnocchi", und: "Ravioli", cat: "Food & Drink" },
  { civ: "Espresso", und: "Americano", cat: "Food & Drink" },
  { civ: "Cappuccino", und: "Latte", cat: "Food & Drink" },
  { civ: "Mocha", und: "Macchiato", cat: "Food & Drink" },
  { civ: "Hot Chocolate", und: "Chai", cat: "Food & Drink" },
  { civ: "Green Tea", und: "Herbal Tea", cat: "Food & Drink" },
  { civ: "Iced Tea", und: "Lemonade", cat: "Food & Drink" },
  { civ: "Smoothie", und: "Milkshake", cat: "Food & Drink" },
  { civ: "Cola", und: "Lemonade", cat: "Food & Drink" },
  { civ: "Sparkling Water", und: "Tonic Water", cat: "Food & Drink" },
  { civ: "Beer", und: "Cider", cat: "Food & Drink" },
  { civ: "Wine", und: "Champagne", cat: "Food & Drink" },
  { civ: "Whisky", und: "Brandy", cat: "Food & Drink" },
  { civ: "Vodka", und: "Gin", cat: "Food & Drink" },
  { civ: "Rum", und: "Tequila", cat: "Food & Drink" },
  { civ: "Cocktail", und: "Mocktail", cat: "Food & Drink" },
  { civ: "Mojito", und: "Margarita", cat: "Food & Drink" },
  { civ: "Martini", und: "Cosmopolitan", cat: "Food & Drink" },
  { civ: "Fish and Chips", und: "Pie and Mash", cat: "Food & Drink" },
  { civ: "Roast Dinner", und: "Sunday Lunch", cat: "Food & Drink" },
  { civ: "Full English", und: "Continental Breakfast", cat: "Food & Drink" },
  { civ: "Afternoon Tea", und: "High Tea", cat: "Food & Drink" },
  { civ: "Cheddar", und: "Stilton", cat: "Food & Drink" },

  // ============================================
  // ANIMALS (100 pairs)
  // ============================================
  { civ: "Dog", und: "Wolf", cat: "Animals" },
  { civ: "Cat", und: "Tiger", cat: "Animals" },
  { civ: "Lion", und: "Leopard", cat: "Animals" },
  { civ: "Cheetah", und: "Jaguar", cat: "Animals" },
  { civ: "Bear", und: "Panda", cat: "Animals" },
  { civ: "Fox", und: "Coyote", cat: "Animals" },
  { civ: "Rabbit", und: "Hare", cat: "Animals" },
  { civ: "Hamster", und: "Guinea Pig", cat: "Animals" },
  { civ: "Mouse", und: "Rat", cat: "Animals" },
  { civ: "Squirrel", und: "Chipmunk", cat: "Animals" },
  { civ: "Horse", und: "Donkey", cat: "Animals" },
  { civ: "Zebra", und: "Horse", cat: "Animals" },
  { civ: "Cow", und: "Bull", cat: "Animals" },
  { civ: "Sheep", und: "Goat", cat: "Animals" },
  { civ: "Pig", und: "Boar", cat: "Animals" },
  { civ: "Deer", und: "Elk", cat: "Animals" },
  { civ: "Moose", und: "Caribou", cat: "Animals" },
  { civ: "Giraffe", und: "Okapi", cat: "Animals" },
  { civ: "Elephant", und: "Mammoth", cat: "Animals" },
  { civ: "Rhino", und: "Hippo", cat: "Animals" },
  { civ: "Gorilla", und: "Chimpanzee", cat: "Animals" },
  { civ: "Monkey", und: "Ape", cat: "Animals" },
  { civ: "Orangutan", und: "Gibbon", cat: "Animals" },
  { civ: "Kangaroo", und: "Wallaby", cat: "Animals" },
  { civ: "Koala", und: "Sloth", cat: "Animals" },
  { civ: "Badger", und: "Wolverine", cat: "Animals" },
  { civ: "Otter", und: "Beaver", cat: "Animals" },
  { civ: "Seal", und: "Sea Lion", cat: "Animals" },
  { civ: "Walrus", und: "Manatee", cat: "Animals" },
  { civ: "Dolphin", und: "Porpoise", cat: "Animals" },
  { civ: "Whale", und: "Shark", cat: "Animals" },
  { civ: "Octopus", und: "Squid", cat: "Animals" },
  { civ: "Crab", und: "Lobster", cat: "Animals" },
  { civ: "Shrimp", und: "Prawn", cat: "Animals" },
  { civ: "Jellyfish", und: "Starfish", cat: "Animals" },
  { civ: "Seahorse", und: "Sea Dragon", cat: "Animals" },
  { civ: "Turtle", und: "Tortoise", cat: "Animals" },
  { civ: "Crocodile", und: "Alligator", cat: "Animals" },
  { civ: "Lizard", und: "Gecko", cat: "Animals" },
  { civ: "Iguana", und: "Chameleon", cat: "Animals" },
  { civ: "Snake", und: "Eel", cat: "Animals" },
  { civ: "Python", und: "Boa", cat: "Animals" },
  { civ: "Cobra", und: "Viper", cat: "Animals" },
  { civ: "Frog", und: "Toad", cat: "Animals" },
  { civ: "Salamander", und: "Newt", cat: "Animals" },
  { civ: "Eagle", und: "Hawk", cat: "Animals" },
  { civ: "Falcon", und: "Kestrel", cat: "Animals" },
  { civ: "Owl", und: "Bat", cat: "Animals" },
  { civ: "Crow", und: "Raven", cat: "Animals" },
  { civ: "Pigeon", und: "Dove", cat: "Animals" },
  { civ: "Sparrow", und: "Finch", cat: "Animals" },
  { civ: "Robin", und: "Bluebird", cat: "Animals" },
  { civ: "Swan", und: "Goose", cat: "Animals" },
  { civ: "Duck", und: "Mallard", cat: "Animals" },
  { civ: "Heron", und: "Crane", cat: "Animals" },
  { civ: "Flamingo", und: "Stork", cat: "Animals" },
  { civ: "Pelican", und: "Albatross", cat: "Animals" },
  { civ: "Penguin", und: "Puffin", cat: "Animals" },
  { civ: "Seagull", und: "Tern", cat: "Animals" },
  { civ: "Parrot", und: "Parakeet", cat: "Animals" },
  { civ: "Macaw", und: "Cockatoo", cat: "Animals" },
  { civ: "Toucan", und: "Hornbill", cat: "Animals" },
  { civ: "Peacock", und: "Pheasant", cat: "Animals" },
  { civ: "Turkey", und: "Chicken", cat: "Animals" },
  { civ: "Rooster", und: "Hen", cat: "Animals" },
  { civ: "Butterfly", und: "Moth", cat: "Animals" },
  { civ: "Bee", und: "Wasp", cat: "Animals" },
  { civ: "Ant", und: "Termite", cat: "Animals" },
  { civ: "Spider", und: "Scorpion", cat: "Animals" },
  { civ: "Beetle", und: "Cockroach", cat: "Animals" },
  { civ: "Ladybird", und: "Firefly", cat: "Animals" },
  { civ: "Dragonfly", und: "Damselfly", cat: "Animals" },
  { civ: "Grasshopper", und: "Cricket", cat: "Animals" },
  { civ: "Caterpillar", und: "Centipede", cat: "Animals" },
  { civ: "Snail", und: "Slug", cat: "Animals" },
  { civ: "Worm", und: "Leech", cat: "Animals" },
  { civ: "Goldfish", und: "Koi", cat: "Animals" },
  { civ: "Clownfish", und: "Angelfish", cat: "Animals" },
  { civ: "Salmon", und: "Trout", cat: "Animals" },
  { civ: "Piranha", und: "Barracuda", cat: "Animals" },
  { civ: "Manta Ray", und: "Stingray", cat: "Animals" },
  { civ: "Hammerhead", und: "Great White", cat: "Animals" },
  { civ: "Llama", und: "Alpaca", cat: "Animals" },
  { civ: "Camel", und: "Dromedary", cat: "Animals" },
  { civ: "Buffalo", und: "Bison", cat: "Animals" },
  { civ: "Yak", und: "Ox", cat: "Animals" },
  { civ: "Hedgehog", und: "Porcupine", cat: "Animals" },
  { civ: "Mole", und: "Shrew", cat: "Animals" },
  { civ: "Ferret", und: "Weasel", cat: "Animals" },
  { civ: "Mink", und: "Stoat", cat: "Animals" },
  { civ: "Raccoon", und: "Possum", cat: "Animals" },
  { civ: "Skunk", und: "Badger", cat: "Animals" },
  { civ: "Armadillo", und: "Pangolin", cat: "Animals" },
  { civ: "Anteater", und: "Aardvark", cat: "Animals" },
  { civ: "Tapir", und: "Wild Boar", cat: "Animals" },
  { civ: "Lemur", und: "Loris", cat: "Animals" },
  { civ: "Meerkat", und: "Prairie Dog", cat: "Animals" },
  { civ: "Hyena", und: "Wild Dog", cat: "Animals" },
  { civ: "Jackal", und: "Dingo", cat: "Animals" },
  { civ: "Wombat", und: "Platypus", cat: "Animals" },

  // ============================================
  // NATURE & PLACES (100 pairs)
  // ============================================
  { civ: "Beach", und: "Desert", cat: "Nature & Places" },
  { civ: "Rain", und: "Snow", cat: "Nature & Places" },
  { civ: "Mountain", und: "Hill", cat: "Nature & Places" },
  { civ: "Ocean", und: "Lake", cat: "Nature & Places" },
  { civ: "Forest", und: "Jungle", cat: "Nature & Places" },
  { civ: "River", und: "Stream", cat: "Nature & Places" },
  { civ: "Pond", und: "Puddle", cat: "Nature & Places" },
  { civ: "Waterfall", und: "Rapids", cat: "Nature & Places" },
  { civ: "Glacier", und: "Iceberg", cat: "Nature & Places" },
  { civ: "Volcano", und: "Geyser", cat: "Nature & Places" },
  { civ: "Cave", und: "Cavern", cat: "Nature & Places" },
  { civ: "Canyon", und: "Gorge", cat: "Nature & Places" },
  { civ: "Valley", und: "Plain", cat: "Nature & Places" },
  { civ: "Meadow", und: "Prairie", cat: "Nature & Places" },
  { civ: "Swamp", und: "Marsh", cat: "Nature & Places" },
  { civ: "Bog", und: "Moor", cat: "Nature & Places" },
  { civ: "Cliff", und: "Bluff", cat: "Nature & Places" },
  { civ: "Island", und: "Peninsula", cat: "Nature & Places" },
  { civ: "Reef", und: "Atoll", cat: "Nature & Places" },
  { civ: "Bay", und: "Cove", cat: "Nature & Places" },
  { civ: "Harbour", und: "Port", cat: "Nature & Places" },
  { civ: "Coast", und: "Shore", cat: "Nature & Places" },
  { civ: "Dune", und: "Sand Bar", cat: "Nature & Places" },
  { civ: "Oasis", und: "Spring", cat: "Nature & Places" },
  { civ: "Tundra", und: "Steppe", cat: "Nature & Places" },
  { civ: "Savannah", und: "Grassland", cat: "Nature & Places" },
  { civ: "Rainforest", und: "Woodland", cat: "Nature & Places" },
  { civ: "Grove", und: "Copse", cat: "Nature & Places" },
  { civ: "Orchard", und: "Vineyard", cat: "Nature & Places" },
  { civ: "Garden", und: "Park", cat: "Nature & Places" },
  { civ: "Sunrise", und: "Sunset", cat: "Nature & Places" },
  { civ: "Dawn", und: "Dusk", cat: "Nature & Places" },
  { civ: "Fog", und: "Mist", cat: "Nature & Places" },
  { civ: "Hail", und: "Sleet", cat: "Nature & Places" },
  { civ: "Thunder", und: "Lightning", cat: "Nature & Places" },
  { civ: "Tornado", und: "Hurricane", cat: "Nature & Places" },
  { civ: "Cyclone", und: "Typhoon", cat: "Nature & Places" },
  { civ: "Blizzard", und: "Snowstorm", cat: "Nature & Places" },
  { civ: "Drought", und: "Heatwave", cat: "Nature & Places" },
  { civ: "Flood", und: "Tsunami", cat: "Nature & Places" },
  { civ: "Earthquake", und: "Tremor", cat: "Nature & Places" },
  { civ: "Avalanche", und: "Landslide", cat: "Nature & Places" },
  { civ: "Rainbow", und: "Aurora", cat: "Nature & Places" },
  { civ: "Star", und: "Planet", cat: "Nature & Places" },
  { civ: "Moon", und: "Sun", cat: "Nature & Places" },
  { civ: "Comet", und: "Meteor", cat: "Nature & Places" },
  { civ: "Galaxy", und: "Nebula", cat: "Nature & Places" },
  { civ: "Constellation", und: "Asteroid Belt", cat: "Nature & Places" },
  { civ: "Tree", und: "Bush", cat: "Nature & Places" },
  { civ: "Flower", und: "Weed", cat: "Nature & Places" },
  { civ: "Grass", und: "Moss", cat: "Nature & Places" },
  { civ: "Fern", und: "Palm", cat: "Nature & Places" },
  { civ: "Oak", und: "Maple", cat: "Nature & Places" },
  { civ: "Pine", und: "Cedar", cat: "Nature & Places" },
  { civ: "Willow", und: "Birch", cat: "Nature & Places" },
  { civ: "Rose", und: "Tulip", cat: "Nature & Places" },
  { civ: "Daisy", und: "Sunflower", cat: "Nature & Places" },
  { civ: "Lily", und: "Orchid", cat: "Nature & Places" },
  { civ: "Lavender", und: "Heather", cat: "Nature & Places" },
  { civ: "Ivy", und: "Vine", cat: "Nature & Places" },
  { civ: "Cactus", und: "Succulent", cat: "Nature & Places" },
  { civ: "Bamboo", und: "Reed", cat: "Nature & Places" },
  { civ: "Seaweed", und: "Kelp", cat: "Nature & Places" },
  { civ: "Coral", und: "Sponge", cat: "Nature & Places" },
  { civ: "Pebble", und: "Stone", cat: "Nature & Places" },
  { civ: "Rock", und: "Boulder", cat: "Nature & Places" },
  { civ: "Sand", und: "Gravel", cat: "Nature & Places" },
  { civ: "Mud", und: "Clay", cat: "Nature & Places" },
  { civ: "Crystal", und: "Gem", cat: "Nature & Places" },
  { civ: "Diamond", und: "Ruby", cat: "Nature & Places" },
  { civ: "Gold", und: "Silver", cat: "Nature & Places" },
  { civ: "Copper", und: "Bronze", cat: "Nature & Places" },
  { civ: "Iron", und: "Steel", cat: "Nature & Places" },
  { civ: "Marble", und: "Granite", cat: "Nature & Places" },
  { civ: "Limestone", und: "Sandstone", cat: "Nature & Places" },
  { civ: "Coal", und: "Charcoal", cat: "Nature & Places" },
  { civ: "City", und: "Town", cat: "Nature & Places" },
  { civ: "Village", und: "Hamlet", cat: "Nature & Places" },
  { civ: "Suburb", und: "Estate", cat: "Nature & Places" },
  { civ: "Countryside", und: "Rural Area", cat: "Nature & Places" },
  { civ: "Farm", und: "Ranch", cat: "Nature & Places" },
  { civ: "Field", und: "Pasture", cat: "Nature & Places" },
  { civ: "Plantation", und: "Orchard", cat: "Nature & Places" },
  { civ: "Greenhouse", und: "Conservatory", cat: "Nature & Places" },
  { civ: "Zoo", und: "Safari Park", cat: "Nature & Places" },
  { civ: "Aquarium", und: "Marine Park", cat: "Nature & Places" },
  { civ: "Botanical Garden", und: "Arboretum", cat: "Nature & Places" },
  { civ: "Nature Reserve", und: "Wildlife Sanctuary", cat: "Nature & Places" },
  { civ: "National Park", und: "State Park", cat: "Nature & Places" },
  { civ: "Campsite", und: "Caravan Park", cat: "Nature & Places" },
  { civ: "Lighthouse", und: "Beacon", cat: "Nature & Places" },
  { civ: "Bridge", und: "Tunnel", cat: "Nature & Places" },
  { civ: "Dam", und: "Reservoir", cat: "Nature & Places" },
  { civ: "Pier", und: "Jetty", cat: "Nature & Places" },
  { civ: "Boardwalk", und: "Promenade", cat: "Nature & Places" },
  { civ: "Trail", und: "Path", cat: "Nature & Places" },
  { civ: "Footpath", und: "Hiking Trail", cat: "Nature & Places" },
  { civ: "Summit", und: "Peak", cat: "Nature & Places" },
  { civ: "Crater", und: "Basin", cat: "Nature & Places" },

  // ============================================
  // TECHNOLOGY & MEDIA (100 pairs)
  // ============================================
  { civ: "Laptop", und: "Tablet", cat: "Technology & Media" },
  { civ: "Film", und: "TV Series", cat: "Technology & Media" },
  { civ: "Twitter", und: "Facebook", cat: "Technology & Media" },
  { civ: "Spotify", und: "Apple Music", cat: "Technology & Media" },
  { civ: "Netflix", und: "YouTube", cat: "Technology & Media" },
  { civ: "Computer", und: "Laptop", cat: "Technology & Media" },
  { civ: "Desktop", und: "Workstation", cat: "Technology & Media" },
  { civ: "Smartphone", und: "Tablet", cat: "Technology & Media" },
  { civ: "iPhone", und: "Android", cat: "Technology & Media" },
  { civ: "Keyboard", und: "Mouse", cat: "Technology & Media" },
  { civ: "Monitor", und: "Screen", cat: "Technology & Media" },
  { civ: "Printer", und: "Scanner", cat: "Technology & Media" },
  { civ: "Router", und: "Modem", cat: "Technology & Media" },
  { civ: "Wi-Fi", und: "Bluetooth", cat: "Technology & Media" },
  { civ: "USB", und: "HDMI", cat: "Technology & Media" },
  { civ: "Hard Drive", und: "SSD", cat: "Technology & Media" },
  { civ: "RAM", und: "Storage", cat: "Technology & Media" },
  { civ: "CPU", und: "GPU", cat: "Technology & Media" },
  { civ: "Software", und: "Hardware", cat: "Technology & Media" },
  { civ: "App", und: "Programme", cat: "Technology & Media" },
  { civ: "Website", und: "Web App", cat: "Technology & Media" },
  { civ: "Browser", und: "Search Engine", cat: "Technology & Media" },
  { civ: "Google", und: "Bing", cat: "Technology & Media" },
  { civ: "Chrome", und: "Firefox", cat: "Technology & Media" },
  { civ: "Email", und: "Text Message", cat: "Technology & Media" },
  { civ: "SMS", und: "WhatsApp", cat: "Technology & Media" },
  { civ: "Instagram", und: "TikTok", cat: "Technology & Media" },
  { civ: "LinkedIn", und: "Indeed", cat: "Technology & Media" },
  { civ: "Reddit", und: "Quora", cat: "Technology & Media" },
  { civ: "Discord", und: "Slack", cat: "Technology & Media" },
  { civ: "Zoom", und: "Teams", cat: "Technology & Media" },
  { civ: "Skype", und: "FaceTime", cat: "Technology & Media" },
  { civ: "Podcast", und: "Radio Show", cat: "Technology & Media" },
  { civ: "Blog", und: "Vlog", cat: "Technology & Media" },
  { civ: "Streaming", und: "Download", cat: "Technology & Media" },
  { civ: "Upload", und: "Download", cat: "Technology & Media" },
  { civ: "Cloud Storage", und: "Local Storage", cat: "Technology & Media" },
  { civ: "Dropbox", und: "Google Drive", cat: "Technology & Media" },
  { civ: "iCloud", und: "OneDrive", cat: "Technology & Media" },
  { civ: "Password", und: "PIN", cat: "Technology & Media" },
  { civ: "Username", und: "Email Address", cat: "Technology & Media" },
  { civ: "Login", und: "Sign Up", cat: "Technology & Media" },
  { civ: "Profile", und: "Account", cat: "Technology & Media" },
  { civ: "Notification", und: "Alert", cat: "Technology & Media" },
  { civ: "Update", und: "Upgrade", cat: "Technology & Media" },
  { civ: "Bug", und: "Glitch", cat: "Technology & Media" },
  { civ: "Virus", und: "Malware", cat: "Technology & Media" },
  { civ: "Firewall", und: "Antivirus", cat: "Technology & Media" },
  { civ: "Encryption", und: "VPN", cat: "Technology & Media" },
  { civ: "Backup", und: "Restore", cat: "Technology & Media" },
  { civ: "Television", und: "Monitor", cat: "Technology & Media" },
  { civ: "Remote Control", und: "Smart Speaker", cat: "Technology & Media" },
  { civ: "Alexa", und: "Siri", cat: "Technology & Media" },
  { civ: "Smart Watch", und: "Fitness Tracker", cat: "Technology & Media" },
  { civ: "Headphones", und: "Earbuds", cat: "Technology & Media" },
  { civ: "Speaker", und: "Soundbar", cat: "Technology & Media" },
  { civ: "Microphone", und: "Webcam", cat: "Technology & Media" },
  { civ: "Camera", und: "Camcorder", cat: "Technology & Media" },
  { civ: "DSLR", und: "Mirrorless", cat: "Technology & Media" },
  { civ: "Drone", und: "RC Car", cat: "Technology & Media" },
  { civ: "VR Headset", und: "AR Glasses", cat: "Technology & Media" },
  { civ: "PlayStation", und: "Xbox", cat: "Technology & Media" },
  { civ: "Nintendo", und: "Sega", cat: "Technology & Media" },
  { civ: "Console", und: "PC Gaming", cat: "Technology & Media" },
  { civ: "Controller", und: "Joystick", cat: "Technology & Media" },
  { civ: "Video Game", und: "Board Game", cat: "Technology & Media" },
  { civ: "E-Reader", und: "Tablet", cat: "Technology & Media" },
  { civ: "Kindle", und: "Kobo", cat: "Technology & Media" },
  { civ: "Audiobook", und: "E-Book", cat: "Technology & Media" },
  { civ: "Newspaper", und: "Magazine", cat: "Technology & Media" },
  { civ: "Article", und: "Blog Post", cat: "Technology & Media" },
  { civ: "Documentary", und: "News Report", cat: "Technology & Media" },
  { civ: "Trailer", und: "Teaser", cat: "Technology & Media" },
  { civ: "Sequel", und: "Prequel", cat: "Technology & Media" },
  { civ: "Remake", und: "Reboot", cat: "Technology & Media" },
  { civ: "Animation", und: "Live Action", cat: "Technology & Media" },
  { civ: "Anime", und: "Cartoon", cat: "Technology & Media" },
  { civ: "Sitcom", und: "Drama", cat: "Technology & Media" },
  { civ: "Comedy", und: "Tragedy", cat: "Technology & Media" },
  { civ: "Thriller", und: "Horror", cat: "Technology & Media" },
  { civ: "Sci-Fi", und: "Fantasy", cat: "Technology & Media" },
  { civ: "Romance", und: "Drama", cat: "Technology & Media" },
  { civ: "Action", und: "Adventure", cat: "Technology & Media" },
  { civ: "Mystery", und: "Crime", cat: "Technology & Media" },
  { civ: "Biography", und: "Autobiography", cat: "Technology & Media" },
  { civ: "Fiction", und: "Non-Fiction", cat: "Technology & Media" },
  { civ: "Novel", und: "Short Story", cat: "Technology & Media" },
  { civ: "Poem", und: "Song Lyrics", cat: "Technology & Media" },
  { civ: "Script", und: "Screenplay", cat: "Technology & Media" },
  { civ: "Character", und: "Actor", cat: "Technology & Media" },
  { civ: "Director", und: "Producer", cat: "Technology & Media" },
  { civ: "Editor", und: "Writer", cat: "Technology & Media" },
  { civ: "Hashtag", und: "Tag", cat: "Technology & Media" },
  { civ: "Like", und: "Share", cat: "Technology & Media" },
  { civ: "Comment", und: "Reply", cat: "Technology & Media" },
  { civ: "Follow", und: "Subscribe", cat: "Technology & Media" },
  { civ: "Viral", und: "Trending", cat: "Technology & Media" },
  { civ: "Meme", und: "GIF", cat: "Technology & Media" },
  { civ: "Emoji", und: "Sticker", cat: "Technology & Media" },

  // ============================================
  // TRANSPORTATION (80 pairs)
  // ============================================
  { civ: "Underground", und: "Bus", cat: "Transportation" },
  { civ: "Bicycle", und: "Scooter", cat: "Transportation" },
  { civ: "Aeroplane", und: "Helicopter", cat: "Transportation" },
  { civ: "Car", und: "Van", cat: "Transportation" },
  { civ: "Lorry", und: "Pickup Truck", cat: "Transportation" },
  { civ: "Motorbike", und: "Moped", cat: "Transportation" },
  { civ: "Taxi", und: "Uber", cat: "Transportation" },
  { civ: "Tram", und: "Trolleybus", cat: "Transportation" },
  { civ: "Train", und: "Tube", cat: "Transportation" },
  { civ: "Coach", und: "Minibus", cat: "Transportation" },
  { civ: "Ferry", und: "Cruise Ship", cat: "Transportation" },
  { civ: "Yacht", und: "Sailboat", cat: "Transportation" },
  { civ: "Speedboat", und: "Jet Ski", cat: "Transportation" },
  { civ: "Canoe", und: "Kayak", cat: "Transportation" },
  { civ: "Rowing Boat", und: "Pedalo", cat: "Transportation" },
  { civ: "Submarine", und: "Diving Bell", cat: "Transportation" },
  { civ: "Hovercraft", und: "Hydrofoil", cat: "Transportation" },
  { civ: "Hot Air Balloon", und: "Airship", cat: "Transportation" },
  { civ: "Glider", und: "Hang Glider", cat: "Transportation" },
  { civ: "Paraglider", und: "Parachute", cat: "Transportation" },
  { civ: "Jet", und: "Propeller Plane", cat: "Transportation" },
  { civ: "Private Jet", und: "Charter Plane", cat: "Transportation" },
  { civ: "Cargo Plane", und: "Passenger Plane", cat: "Transportation" },
  { civ: "Sedan", und: "Hatchback", cat: "Transportation" },
  { civ: "Estate Car", und: "SUV", cat: "Transportation" },
  { civ: "Convertible", und: "Coupe", cat: "Transportation" },
  { civ: "Sports Car", und: "Muscle Car", cat: "Transportation" },
  { civ: "Electric Car", und: "Hybrid Car", cat: "Transportation" },
  { civ: "Limousine", und: "Town Car", cat: "Transportation" },
  { civ: "Ambulance", und: "Fire Engine", cat: "Transportation" },
  { civ: "Police Car", und: "Patrol Car", cat: "Transportation" },
  { civ: "Ice Cream Van", und: "Food Truck", cat: "Transportation" },
  { civ: "Caravan", und: "Motorhome", cat: "Transportation" },
  { civ: "Campervan", und: "RV", cat: "Transportation" },
  { civ: "Tractor", und: "Combine Harvester", cat: "Transportation" },
  { civ: "Forklift", und: "Crane", cat: "Transportation" },
  { civ: "Bulldozer", und: "Excavator", cat: "Transportation" },
  { civ: "Steamroller", und: "Paver", cat: "Transportation" },
  { civ: "Tanker", und: "Container Ship", cat: "Transportation" },
  { civ: "Tug Boat", und: "Barge", cat: "Transportation" },
  { civ: "Lifeboat", und: "Dinghy", cat: "Transportation" },
  { civ: "Raft", und: "Inflatable", cat: "Transportation" },
  { civ: "Skateboard", und: "Longboard", cat: "Transportation" },
  { civ: "Roller Skates", und: "Rollerblades", cat: "Transportation" },
  { civ: "Unicycle", und: "Tricycle", cat: "Transportation" },
  { civ: "Segway", und: "Electric Scooter", cat: "Transportation" },
  { civ: "Wheelchair", und: "Mobility Scooter", cat: "Transportation" },
  { civ: "Pram", und: "Pushchair", cat: "Transportation" },
  { civ: "Shopping Trolley", und: "Basket", cat: "Transportation" },
  { civ: "Sled", und: "Toboggan", cat: "Transportation" },
  { civ: "Snowmobile", und: "Quad Bike", cat: "Transportation" },
  { civ: "Go-Kart", und: "Bumper Car", cat: "Transportation" },
  { civ: "Cable Car", und: "Gondola", cat: "Transportation" },
  { civ: "Chairlift", und: "Ski Lift", cat: "Transportation" },
  { civ: "Escalator", und: "Lift", cat: "Transportation" },
  { civ: "Rickshaw", und: "Tuk-Tuk", cat: "Transportation" },
  { civ: "Horse and Cart", und: "Carriage", cat: "Transportation" },
  { civ: "Stagecoach", und: "Chariot", cat: "Transportation" },
  { civ: "Steam Train", und: "Diesel Train", cat: "Transportation" },
  { civ: "High-Speed Rail", und: "Maglev", cat: "Transportation" },
  { civ: "Monorail", und: "Light Rail", cat: "Transportation" },
  { civ: "Freight Train", und: "Passenger Train", cat: "Transportation" },
  { civ: "Sleeper Train", und: "Day Train", cat: "Transportation" },
  { civ: "Double-Decker Bus", und: "Single-Decker Bus", cat: "Transportation" },
  { civ: "Night Bus", und: "Express Bus", cat: "Transportation" },
  { civ: "School Bus", und: "Shuttle Bus", cat: "Transportation" },
  { civ: "Airport", und: "Train Station", cat: "Transportation" },
  { civ: "Bus Station", und: "Coach Station", cat: "Transportation" },
  { civ: "Harbour", und: "Marina", cat: "Transportation" },
  { civ: "Runway", und: "Helipad", cat: "Transportation" },
  { civ: "Terminal", und: "Gate", cat: "Transportation" },
  { civ: "Platform", und: "Departure Lounge", cat: "Transportation" },
  { civ: "Ticket", und: "Pass", cat: "Transportation" },
  { civ: "Oyster Card", und: "Contactless", cat: "Transportation" },
  { civ: "First Class", und: "Economy", cat: "Transportation" },
  { civ: "Window Seat", und: "Aisle Seat", cat: "Transportation" },
  { civ: "Suitcase", und: "Rucksack", cat: "Transportation" },
  { civ: "Hand Luggage", und: "Hold Luggage", cat: "Transportation" },
  { civ: "Passport", und: "Visa", cat: "Transportation" },

  // ============================================
  // MUSIC & ARTS (80 pairs)
  // ============================================
  { civ: "Piano", und: "Keyboard", cat: "Music & Arts" },
  { civ: "Guitar", und: "Ukulele", cat: "Music & Arts" },
  { civ: "Painting", und: "Drawing", cat: "Music & Arts" },
  { civ: "Violin", und: "Viola", cat: "Music & Arts" },
  { civ: "Cello", und: "Double Bass", cat: "Music & Arts" },
  { civ: "Trumpet", und: "Trombone", cat: "Music & Arts" },
  { civ: "Saxophone", und: "Clarinet", cat: "Music & Arts" },
  { civ: "Flute", und: "Recorder", cat: "Music & Arts" },
  { civ: "Oboe", und: "Bassoon", cat: "Music & Arts" },
  { civ: "Drums", und: "Percussion", cat: "Music & Arts" },
  { civ: "Tambourine", und: "Maracas", cat: "Music & Arts" },
  { civ: "Xylophone", und: "Glockenspiel", cat: "Music & Arts" },
  { civ: "Harp", und: "Lyre", cat: "Music & Arts" },
  { civ: "Banjo", und: "Mandolin", cat: "Music & Arts" },
  { civ: "Accordion", und: "Harmonica", cat: "Music & Arts" },
  { civ: "Bagpipes", und: "Pan Flute", cat: "Music & Arts" },
  { civ: "Electric Guitar", und: "Acoustic Guitar", cat: "Music & Arts" },
  { civ: "Bass Guitar", und: "Electric Guitar", cat: "Music & Arts" },
  { civ: "Synthesiser", und: "Organ", cat: "Music & Arts" },
  { civ: "DJ Deck", und: "Mixer", cat: "Music & Arts" },
  { civ: "Orchestra", und: "Band", cat: "Music & Arts" },
  { civ: "Choir", und: "Acapella Group", cat: "Music & Arts" },
  { civ: "Solo", und: "Duet", cat: "Music & Arts" },
  { civ: "Quartet", und: "Quintet", cat: "Music & Arts" },
  { civ: "Symphony", und: "Concerto", cat: "Music & Arts" },
  { civ: "Sonata", und: "Etude", cat: "Music & Arts" },
  { civ: "Opera", und: "Musical", cat: "Music & Arts" },
  { civ: "Ballet", und: "Contemporary Dance", cat: "Music & Arts" },
  { civ: "Jazz", und: "Blues", cat: "Music & Arts" },
  { civ: "Rock", und: "Pop", cat: "Music & Arts" },
  { civ: "Hip Hop", und: "R&B", cat: "Music & Arts" },
  { civ: "Country", und: "Folk", cat: "Music & Arts" },
  { civ: "Classical", und: "Baroque", cat: "Music & Arts" },
  { civ: "Electronic", und: "House", cat: "Music & Arts" },
  { civ: "Techno", und: "Trance", cat: "Music & Arts" },
  { civ: "Reggae", und: "Ska", cat: "Music & Arts" },
  { civ: "Metal", und: "Punk", cat: "Music & Arts" },
  { civ: "Grunge", und: "Alternative", cat: "Music & Arts" },
  { civ: "Indie", und: "Lo-Fi", cat: "Music & Arts" },
  { civ: "Soul", und: "Funk", cat: "Music & Arts" },
  { civ: "Gospel", und: "Spiritual", cat: "Music & Arts" },
  { civ: "Melody", und: "Harmony", cat: "Music & Arts" },
  { civ: "Rhythm", und: "Beat", cat: "Music & Arts" },
  { civ: "Tempo", und: "Pace", cat: "Music & Arts" },
  { civ: "Verse", und: "Chorus", cat: "Music & Arts" },
  { civ: "Bridge", und: "Outro", cat: "Music & Arts" },
  { civ: "Album", und: "EP", cat: "Music & Arts" },
  { civ: "Single", und: "B-Side", cat: "Music & Arts" },
  { civ: "Concert", und: "Gig", cat: "Music & Arts" },
  { civ: "Festival", und: "Rave", cat: "Music & Arts" },
  { civ: "Oil Paint", und: "Acrylic Paint", cat: "Music & Arts" },
  { civ: "Watercolour", und: "Gouache", cat: "Music & Arts" },
  { civ: "Pastel", und: "Crayon", cat: "Music & Arts" },
  { civ: "Charcoal", und: "Graphite", cat: "Music & Arts" },
  { civ: "Canvas", und: "Paper", cat: "Music & Arts" },
  { civ: "Easel", und: "Drawing Board", cat: "Music & Arts" },
  { civ: "Palette", und: "Brush", cat: "Music & Arts" },
  { civ: "Sculpture", und: "Statue", cat: "Music & Arts" },
  { civ: "Clay", und: "Plaster", cat: "Music & Arts" },
  { civ: "Bronze", und: "Marble", cat: "Music & Arts" },
  { civ: "Pottery", und: "Ceramics", cat: "Music & Arts" },
  { civ: "Mosaic", und: "Collage", cat: "Music & Arts" },
  { civ: "Etching", und: "Engraving", cat: "Music & Arts" },
  { civ: "Lithograph", und: "Screen Print", cat: "Music & Arts" },
  { civ: "Portrait", und: "Self-Portrait", cat: "Music & Arts" },
  { civ: "Landscape", und: "Seascape", cat: "Music & Arts" },
  { civ: "Still Life", und: "Abstract", cat: "Music & Arts" },
  { civ: "Impressionism", und: "Expressionism", cat: "Music & Arts" },
  { civ: "Cubism", und: "Surrealism", cat: "Music & Arts" },
  { civ: "Realism", und: "Naturalism", cat: "Music & Arts" },
  { civ: "Renaissance", und: "Baroque", cat: "Music & Arts" },
  { civ: "Modern Art", und: "Contemporary Art", cat: "Music & Arts" },
  { civ: "Gallery", und: "Museum", cat: "Music & Arts" },
  { civ: "Exhibition", und: "Collection", cat: "Music & Arts" },
  { civ: "Frame", und: "Mount", cat: "Music & Arts" },
  { civ: "Photography", und: "Videography", cat: "Music & Arts" },
  { civ: "Theatre", und: "Cinema", cat: "Music & Arts" },
  { civ: "Stage", und: "Set", cat: "Music & Arts" },
  { civ: "Costume", und: "Prop", cat: "Music & Arts" },
  { civ: "Rehearsal", und: "Performance", cat: "Music & Arts" },

  // ============================================
  // SPORTS & FITNESS (100 pairs)
  // ============================================
  { civ: "Football", und: "Rugby", cat: "Sports & Fitness" },
  { civ: "Yoga", und: "Pilates", cat: "Sports & Fitness" },
  { civ: "Boxing", und: "Wrestling", cat: "Sports & Fitness" },
  { civ: "Tennis", und: "Badminton", cat: "Sports & Fitness" },
  { civ: "Cricket", und: "Baseball", cat: "Sports & Fitness" },
  { civ: "Golf", und: "Mini Golf", cat: "Sports & Fitness" },
  { civ: "Swimming", und: "Diving", cat: "Sports & Fitness" },
  { civ: "Running", und: "Jogging", cat: "Sports & Fitness" },
  { civ: "Marathon", und: "Sprint", cat: "Sports & Fitness" },
  { civ: "Cycling", und: "Mountain Biking", cat: "Sports & Fitness" },
  { civ: "Skiing", und: "Snowboarding", cat: "Sports & Fitness" },
  { civ: "Ice Skating", und: "Roller Skating", cat: "Sports & Fitness" },
  { civ: "Hockey", und: "Ice Hockey", cat: "Sports & Fitness" },
  { civ: "Basketball", und: "Netball", cat: "Sports & Fitness" },
  { civ: "Volleyball", und: "Beach Volleyball", cat: "Sports & Fitness" },
  { civ: "Handball", und: "Squash", cat: "Sports & Fitness" },
  { civ: "Table Tennis", und: "Ping Pong", cat: "Sports & Fitness" },
  { civ: "Snooker", und: "Pool", cat: "Sports & Fitness" },
  { civ: "Darts", und: "Archery", cat: "Sports & Fitness" },
  { civ: "Bowling", und: "Bocce", cat: "Sports & Fitness" },
  { civ: "Fencing", und: "Kendo", cat: "Sports & Fitness" },
  { civ: "Karate", und: "Taekwondo", cat: "Sports & Fitness" },
  { civ: "Judo", und: "Jiu-Jitsu", cat: "Sports & Fitness" },
  { civ: "Kung Fu", und: "Muay Thai", cat: "Sports & Fitness" },
  { civ: "MMA", und: "UFC", cat: "Sports & Fitness" },
  { civ: "Weightlifting", und: "Powerlifting", cat: "Sports & Fitness" },
  { civ: "Crossfit", und: "HIIT", cat: "Sports & Fitness" },
  { civ: "Aerobics", und: "Zumba", cat: "Sports & Fitness" },
  { civ: "Spin Class", und: "Rowing Machine", cat: "Sports & Fitness" },
  { civ: "Treadmill", und: "Elliptical", cat: "Sports & Fitness" },
  { civ: "Dumbbells", und: "Kettlebells", cat: "Sports & Fitness" },
  { civ: "Barbell", und: "Medicine Ball", cat: "Sports & Fitness" },
  { civ: "Resistance Band", und: "Pull-Up Bar", cat: "Sports & Fitness" },
  { civ: "Yoga Mat", und: "Exercise Ball", cat: "Sports & Fitness" },
  { civ: "Gym", und: "Fitness Centre", cat: "Sports & Fitness" },
  { civ: "Personal Trainer", und: "Fitness Instructor", cat: "Sports & Fitness" },
  { civ: "Warm-Up", und: "Cool-Down", cat: "Sports & Fitness" },
  { civ: "Stretching", und: "Flexibility", cat: "Sports & Fitness" },
  { civ: "Cardio", und: "Strength Training", cat: "Sports & Fitness" },
  { civ: "Endurance", und: "Stamina", cat: "Sports & Fitness" },
  { civ: "Surfing", und: "Bodyboarding", cat: "Sports & Fitness" },
  { civ: "Wakeboarding", und: "Water Skiing", cat: "Sports & Fitness" },
  { civ: "Kayaking", und: "Canoeing", cat: "Sports & Fitness" },
  { civ: "Rafting", und: "Tubing", cat: "Sports & Fitness" },
  { civ: "Sailing", und: "Windsurfing", cat: "Sports & Fitness" },
  { civ: "Kitesurfing", und: "Parasailing", cat: "Sports & Fitness" },
  { civ: "Scuba Diving", und: "Snorkelling", cat: "Sports & Fitness" },
  { civ: "Free Diving", und: "Underwater Hockey", cat: "Sports & Fitness" },
  { civ: "Water Polo", und: "Synchronised Swimming", cat: "Sports & Fitness" },
  { civ: "Triathlon", und: "Decathlon", cat: "Sports & Fitness" },
  { civ: "Pentathlon", und: "Heptathlon", cat: "Sports & Fitness" },
  { civ: "High Jump", und: "Long Jump", cat: "Sports & Fitness" },
  { civ: "Pole Vault", und: "Triple Jump", cat: "Sports & Fitness" },
  { civ: "Shot Put", und: "Discus", cat: "Sports & Fitness" },
  { civ: "Javelin", und: "Hammer Throw", cat: "Sports & Fitness" },
  { civ: "Hurdles", und: "Steeplechase", cat: "Sports & Fitness" },
  { civ: "Relay Race", und: "Baton Pass", cat: "Sports & Fitness" },
  { civ: "Cross Country", und: "Track", cat: "Sports & Fitness" },
  { civ: "Horse Racing", und: "Greyhound Racing", cat: "Sports & Fitness" },
  { civ: "Show Jumping", und: "Dressage", cat: "Sports & Fitness" },
  { civ: "Polo", und: "Croquet", cat: "Sports & Fitness" },
  { civ: "Lacrosse", und: "Field Hockey", cat: "Sports & Fitness" },
  { civ: "American Football", und: "Australian Rules", cat: "Sports & Fitness" },
  { civ: "Rock Climbing", und: "Bouldering", cat: "Sports & Fitness" },
  { civ: "Mountaineering", und: "Hiking", cat: "Sports & Fitness" },
  { civ: "Abseiling", und: "Canyoning", cat: "Sports & Fitness" },
  { civ: "Zip Line", und: "Rope Course", cat: "Sports & Fitness" },
  { civ: "Parkour", und: "Free Running", cat: "Sports & Fitness" },
  { civ: "Skateboarding", und: "BMX", cat: "Sports & Fitness" },
  { civ: "Motocross", und: "Supercross", cat: "Sports & Fitness" },
  { civ: "Formula One", und: "NASCAR", cat: "Sports & Fitness" },
  { civ: "Rally Racing", und: "Drag Racing", cat: "Sports & Fitness" },
  { civ: "Go-Karting", und: "Stock Car Racing", cat: "Sports & Fitness" },
  { civ: "Chess", und: "Draughts", cat: "Sports & Fitness" },
  { civ: "Poker", und: "Blackjack", cat: "Sports & Fitness" },
  { civ: "Bridge", und: "Whist", cat: "Sports & Fitness" },
  { civ: "Backgammon", und: "Mahjong", cat: "Sports & Fitness" },
  { civ: "Scrabble", und: "Boggle", cat: "Sports & Fitness" },
  { civ: "Sudoku", und: "Crossword", cat: "Sports & Fitness" },
  { civ: "Jigsaw Puzzle", und: "Rubik's Cube", cat: "Sports & Fitness" },
  { civ: "League", und: "Cup", cat: "Sports & Fitness" },
  { civ: "Tournament", und: "Championship", cat: "Sports & Fitness" },
  { civ: "Final", und: "Semi-Final", cat: "Sports & Fitness" },
  { civ: "Match", und: "Game", cat: "Sports & Fitness" },
  { civ: "Coach", und: "Manager", cat: "Sports & Fitness" },
  { civ: "Referee", und: "Umpire", cat: "Sports & Fitness" },
  { civ: "Captain", und: "Goalkeeper", cat: "Sports & Fitness" },
  { civ: "Striker", und: "Midfielder", cat: "Sports & Fitness" },
  { civ: "Defender", und: "Winger", cat: "Sports & Fitness" },
  { civ: "Substitute", und: "Reserve", cat: "Sports & Fitness" },
  { civ: "Hat-Trick", und: "Brace", cat: "Sports & Fitness" },
  { civ: "Penalty", und: "Free Kick", cat: "Sports & Fitness" },
  { civ: "Corner", und: "Throw-In", cat: "Sports & Fitness" },
  { civ: "Offside", und: "Foul", cat: "Sports & Fitness" },
  { civ: "Yellow Card", und: "Red Card", cat: "Sports & Fitness" },
  { civ: "Overtime", und: "Extra Time", cat: "Sports & Fitness" },
  { civ: "Penalty Shootout", und: "Golden Goal", cat: "Sports & Fitness" },
  { civ: "Trophy", und: "Medal", cat: "Sports & Fitness" },
  { civ: "Podium", und: "Winners' Circle", cat: "Sports & Fitness" },

  // ============================================
  // FASHION & CLOTHING (80 pairs)
  // ============================================
  { civ: "Jeans", und: "Chinos", cat: "Fashion & Clothing" },
  { civ: "Trainers", und: "Sandals", cat: "Fashion & Clothing" },
  { civ: "Glasses", und: "Sunglasses", cat: "Fashion & Clothing" },
  { civ: "T-Shirt", und: "Polo Shirt", cat: "Fashion & Clothing" },
  { civ: "Shirt", und: "Blouse", cat: "Fashion & Clothing" },
  { civ: "Jumper", und: "Cardigan", cat: "Fashion & Clothing" },
  { civ: "Hoodie", und: "Sweatshirt", cat: "Fashion & Clothing" },
  { civ: "Jacket", und: "Blazer", cat: "Fashion & Clothing" },
  { civ: "Coat", und: "Overcoat", cat: "Fashion & Clothing" },
  { civ: "Anorak", und: "Parka", cat: "Fashion & Clothing" },
  { civ: "Raincoat", und: "Windbreaker", cat: "Fashion & Clothing" },
  { civ: "Suit", und: "Tuxedo", cat: "Fashion & Clothing" },
  { civ: "Waistcoat", und: "Gilet", cat: "Fashion & Clothing" },
  { civ: "Dress", und: "Gown", cat: "Fashion & Clothing" },
  { civ: "Skirt", und: "Culottes", cat: "Fashion & Clothing" },
  { civ: "Trousers", und: "Shorts", cat: "Fashion & Clothing" },
  { civ: "Leggings", und: "Tights", cat: "Fashion & Clothing" },
  { civ: "Joggers", und: "Tracksuit Bottoms", cat: "Fashion & Clothing" },
  { civ: "Dungarees", und: "Overalls", cat: "Fashion & Clothing" },
  { civ: "Jumpsuit", und: "Romper", cat: "Fashion & Clothing" },
  { civ: "Bikini", und: "Swimsuit", cat: "Fashion & Clothing" },
  { civ: "Swimming Trunks", und: "Speedos", cat: "Fashion & Clothing" },
  { civ: "Pyjamas", und: "Nightgown", cat: "Fashion & Clothing" },
  { civ: "Dressing Gown", und: "Bathrobe", cat: "Fashion & Clothing" },
  { civ: "Slippers", und: "Flip-Flops", cat: "Fashion & Clothing" },
  { civ: "Boots", und: "Ankle Boots", cat: "Fashion & Clothing" },
  { civ: "Wellies", und: "Hiking Boots", cat: "Fashion & Clothing" },
  { civ: "Loafers", und: "Brogues", cat: "Fashion & Clothing" },
  { civ: "High Heels", und: "Wedges", cat: "Fashion & Clothing" },
  { civ: "Flats", und: "Ballet Pumps", cat: "Fashion & Clothing" },
  { civ: "Plimsolls", und: "Espadrilles", cat: "Fashion & Clothing" },
  { civ: "Hat", und: "Cap", cat: "Fashion & Clothing" },
  { civ: "Beanie", und: "Bobble Hat", cat: "Fashion & Clothing" },
  { civ: "Beret", und: "Fedora", cat: "Fashion & Clothing" },
  { civ: "Top Hat", und: "Bowler Hat", cat: "Fashion & Clothing" },
  { civ: "Sun Hat", und: "Bucket Hat", cat: "Fashion & Clothing" },
  { civ: "Headband", und: "Bandana", cat: "Fashion & Clothing" },
  { civ: "Scarf", und: "Shawl", cat: "Fashion & Clothing" },
  { civ: "Necktie", und: "Bow Tie", cat: "Fashion & Clothing" },
  { civ: "Cravat", und: "Ascot", cat: "Fashion & Clothing" },
  { civ: "Gloves", und: "Mittens", cat: "Fashion & Clothing" },
  { civ: "Socks", und: "Stockings", cat: "Fashion & Clothing" },
  { civ: "Belt", und: "Braces", cat: "Fashion & Clothing" },
  { civ: "Handbag", und: "Clutch", cat: "Fashion & Clothing" },
  { civ: "Backpack", und: "Satchel", cat: "Fashion & Clothing" },
  { civ: "Briefcase", und: "Messenger Bag", cat: "Fashion & Clothing" },
  { civ: "Wallet", und: "Purse", cat: "Fashion & Clothing" },
  { civ: "Watch", und: "Bracelet", cat: "Fashion & Clothing" },
  { civ: "Necklace", und: "Pendant", cat: "Fashion & Clothing" },
  { civ: "Earrings", und: "Studs", cat: "Fashion & Clothing" },
  { civ: "Ring", und: "Band", cat: "Fashion & Clothing" },
  { civ: "Brooch", und: "Pin", cat: "Fashion & Clothing" },
  { civ: "Cufflinks", und: "Tie Clip", cat: "Fashion & Clothing" },
  { civ: "Umbrella", und: "Parasol", cat: "Fashion & Clothing" },
  { civ: "Rainhat", und: "Sou'wester", cat: "Fashion & Clothing" },
  { civ: "Earmuffs", und: "Ear Warmers", cat: "Fashion & Clothing" },
  { civ: "Bra", und: "Sports Bra", cat: "Fashion & Clothing" },
  { civ: "Underwear", und: "Boxers", cat: "Fashion & Clothing" },
  { civ: "Vest", und: "Tank Top", cat: "Fashion & Clothing" },
  { civ: "Corset", und: "Bustier", cat: "Fashion & Clothing" },
  { civ: "Kimono", und: "Kaftan", cat: "Fashion & Clothing" },
  { civ: "Sarong", und: "Wrap", cat: "Fashion & Clothing" },
  { civ: "Poncho", und: "Cape", cat: "Fashion & Clothing" },
  { civ: "Apron", und: "Pinafore", cat: "Fashion & Clothing" },
  { civ: "Uniform", und: "Costume", cat: "Fashion & Clothing" },
  { civ: "Vintage", und: "Retro", cat: "Fashion & Clothing" },
  { civ: "Designer", und: "High Street", cat: "Fashion & Clothing" },
  { civ: "Couture", und: "Ready-to-Wear", cat: "Fashion & Clothing" },
  { civ: "Tailored", und: "Off-the-Peg", cat: "Fashion & Clothing" },
  { civ: "Casual", und: "Smart Casual", cat: "Fashion & Clothing" },
  { civ: "Formal", und: "Black Tie", cat: "Fashion & Clothing" },
  { civ: "Bohemian", und: "Hipster", cat: "Fashion & Clothing" },
  { civ: "Minimalist", und: "Maximalist", cat: "Fashion & Clothing" },
  { civ: "Cotton", und: "Linen", cat: "Fashion & Clothing" },
  { civ: "Silk", und: "Satin", cat: "Fashion & Clothing" },
  { civ: "Wool", und: "Cashmere", cat: "Fashion & Clothing" },
  { civ: "Denim", und: "Corduroy", cat: "Fashion & Clothing" },
  { civ: "Leather", und: "Suede", cat: "Fashion & Clothing" },
  { civ: "Velvet", und: "Velour", cat: "Fashion & Clothing" },
  { civ: "Tweed", und: "Flannel", cat: "Fashion & Clothing" },

  // ============================================
  // HOME & OBJECTS (100 pairs)
  // ============================================
  { civ: "Book", und: "Magazine", cat: "Home & Objects" },
  { civ: "Sofa", und: "Armchair", cat: "Home & Objects" },
  { civ: "Pencil", und: "Pen", cat: "Home & Objects" },
  { civ: "Table", und: "Desk", cat: "Home & Objects" },
  { civ: "Chair", und: "Stool", cat: "Home & Objects" },
  { civ: "Bed", und: "Mattress", cat: "Home & Objects" },
  { civ: "Pillow", und: "Cushion", cat: "Home & Objects" },
  { civ: "Blanket", und: "Duvet", cat: "Home & Objects" },
  { civ: "Sheet", und: "Bedspread", cat: "Home & Objects" },
  { civ: "Wardrobe", und: "Chest of Drawers", cat: "Home & Objects" },
  { civ: "Cupboard", und: "Cabinet", cat: "Home & Objects" },
  { civ: "Shelf", und: "Bookcase", cat: "Home & Objects" },
  { civ: "Mirror", und: "Picture Frame", cat: "Home & Objects" },
  { civ: "Lamp", und: "Chandelier", cat: "Home & Objects" },
  { civ: "Candle", und: "Lantern", cat: "Home & Objects" },
  { civ: "Clock", und: "Watch", cat: "Home & Objects" },
  { civ: "Vase", und: "Pot", cat: "Home & Objects" },
  { civ: "Rug", und: "Carpet", cat: "Home & Objects" },
  { civ: "Curtain", und: "Blind", cat: "Home & Objects" },
  { civ: "Doormat", und: "Welcome Mat", cat: "Home & Objects" },
  { civ: "Key", und: "Lock", cat: "Home & Objects" },
  { civ: "Door", und: "Gate", cat: "Home & Objects" },
  { civ: "Window", und: "Skylight", cat: "Home & Objects" },
  { civ: "Stairs", und: "Ladder", cat: "Home & Objects" },
  { civ: "Balcony", und: "Terrace", cat: "Home & Objects" },
  { civ: "Patio", und: "Decking", cat: "Home & Objects" },
  { civ: "Fence", und: "Wall", cat: "Home & Objects" },
  { civ: "Hedge", und: "Trellis", cat: "Home & Objects" },
  { civ: "Lawn", und: "Flower Bed", cat: "Home & Objects" },
  { civ: "Shed", und: "Garage", cat: "Home & Objects" },
  { civ: "Greenhouse", und: "Conservatory", cat: "Home & Objects" },
  { civ: "Barbecue", und: "Fire Pit", cat: "Home & Objects" },
  { civ: "Hammock", und: "Swing Chair", cat: "Home & Objects" },
  { civ: "Garden Chair", und: "Sun Lounger", cat: "Home & Objects" },
  { civ: "Fork", und: "Spoon", cat: "Home & Objects" },
  { civ: "Knife", und: "Butter Knife", cat: "Home & Objects" },
  { civ: "Plate", und: "Bowl", cat: "Home & Objects" },
  { civ: "Cup", und: "Mug", cat: "Home & Objects" },
  { civ: "Glass", und: "Tumbler", cat: "Home & Objects" },
  { civ: "Wine Glass", und: "Champagne Flute", cat: "Home & Objects" },
  { civ: "Teapot", und: "Kettle", cat: "Home & Objects" },
  { civ: "Coffee Pot", und: "Cafetière", cat: "Home & Objects" },
  { civ: "Jug", und: "Pitcher", cat: "Home & Objects" },
  { civ: "Saucepan", und: "Frying Pan", cat: "Home & Objects" },
  { civ: "Wok", und: "Skillet", cat: "Home & Objects" },
  { civ: "Casserole Dish", und: "Roasting Tin", cat: "Home & Objects" },
  { civ: "Baking Tray", und: "Muffin Tin", cat: "Home & Objects" },
  { civ: "Mixing Bowl", und: "Measuring Jug", cat: "Home & Objects" },
  { civ: "Whisk", und: "Spatula", cat: "Home & Objects" },
  { civ: "Rolling Pin", und: "Pastry Brush", cat: "Home & Objects" },
  { civ: "Chopping Board", und: "Bread Board", cat: "Home & Objects" },
  { civ: "Colander", und: "Sieve", cat: "Home & Objects" },
  { civ: "Grater", und: "Peeler", cat: "Home & Objects" },
  { civ: "Tin Opener", und: "Bottle Opener", cat: "Home & Objects" },
  { civ: "Corkscrew", und: "Nutcracker", cat: "Home & Objects" },
  { civ: "Oven", und: "Microwave", cat: "Home & Objects" },
  { civ: "Hob", und: "Grill", cat: "Home & Objects" },
  { civ: "Toaster", und: "Sandwich Maker", cat: "Home & Objects" },
  { civ: "Blender", und: "Food Processor", cat: "Home & Objects" },
  { civ: "Mixer", und: "Hand Whisk", cat: "Home & Objects" },
  { civ: "Fridge", und: "Freezer", cat: "Home & Objects" },
  { civ: "Dishwasher", und: "Washing Machine", cat: "Home & Objects" },
  { civ: "Tumble Dryer", und: "Airer", cat: "Home & Objects" },
  { civ: "Iron", und: "Steamer", cat: "Home & Objects" },
  { civ: "Vacuum Cleaner", und: "Mop", cat: "Home & Objects" },
  { civ: "Broom", und: "Dustpan", cat: "Home & Objects" },
  { civ: "Bucket", und: "Bin", cat: "Home & Objects" },
  { civ: "Sponge", und: "Cloth", cat: "Home & Objects" },
  { civ: "Soap", und: "Shower Gel", cat: "Home & Objects" },
  { civ: "Shampoo", und: "Conditioner", cat: "Home & Objects" },
  { civ: "Toothbrush", und: "Toothpaste", cat: "Home & Objects" },
  { civ: "Razor", und: "Shaver", cat: "Home & Objects" },
  { civ: "Hairbrush", und: "Comb", cat: "Home & Objects" },
  { civ: "Hair Dryer", und: "Straighteners", cat: "Home & Objects" },
  { civ: "Mirror", und: "Magnifying Glass", cat: "Home & Objects" },
  { civ: "Towel", und: "Flannel", cat: "Home & Objects" },
  { civ: "Bath Mat", und: "Shower Curtain", cat: "Home & Objects" },
  { civ: "Toilet", und: "Bidet", cat: "Home & Objects" },
  { civ: "Basin", und: "Sink", cat: "Home & Objects" },
  { civ: "Bathtub", und: "Shower", cat: "Home & Objects" },
  { civ: "Tap", und: "Shower Head", cat: "Home & Objects" },
  { civ: "Radiator", und: "Heater", cat: "Home & Objects" },
  { civ: "Fan", und: "Air Conditioner", cat: "Home & Objects" },
  { civ: "Thermostat", und: "Timer", cat: "Home & Objects" },
  { civ: "Smoke Alarm", und: "Carbon Monoxide Detector", cat: "Home & Objects" },
  { civ: "Fire Extinguisher", und: "Fire Blanket", cat: "Home & Objects" },
  { civ: "First Aid Kit", und: "Medicine Cabinet", cat: "Home & Objects" },
  { civ: "Toolbox", und: "Toolkit", cat: "Home & Objects" },
  { civ: "Hammer", und: "Mallet", cat: "Home & Objects" },
  { civ: "Screwdriver", und: "Spanner", cat: "Home & Objects" },
  { civ: "Drill", und: "Sander", cat: "Home & Objects" },
  { civ: "Saw", und: "Chisel", cat: "Home & Objects" },
  { civ: "Pliers", und: "Wire Cutters", cat: "Home & Objects" },
  { civ: "Tape Measure", und: "Spirit Level", cat: "Home & Objects" },
  { civ: "Paintbrush", und: "Roller", cat: "Home & Objects" },
  { civ: "Wallpaper", und: "Paint", cat: "Home & Objects" },
  { civ: "Nail", und: "Screw", cat: "Home & Objects" },
  { civ: "Glue", und: "Tape", cat: "Home & Objects" },
  { civ: "String", und: "Rope", cat: "Home & Objects" },

  // ============================================
  // JOBS & PROFESSIONS (80 pairs)
  // ============================================
  { civ: "Chef", und: "Cook", cat: "Jobs & Professions" },
  { civ: "Doctor", und: "Nurse", cat: "Jobs & Professions" },
  { civ: "Teacher", und: "Professor", cat: "Jobs & Professions" },
  { civ: "Lawyer", und: "Barrister", cat: "Jobs & Professions" },
  { civ: "Solicitor", und: "Paralegal", cat: "Jobs & Professions" },
  { civ: "Accountant", und: "Bookkeeper", cat: "Jobs & Professions" },
  { civ: "Manager", und: "Supervisor", cat: "Jobs & Professions" },
  { civ: "Director", und: "Executive", cat: "Jobs & Professions" },
  { civ: "CEO", und: "CFO", cat: "Jobs & Professions" },
  { civ: "Engineer", und: "Technician", cat: "Jobs & Professions" },
  { civ: "Architect", und: "Designer", cat: "Jobs & Professions" },
  { civ: "Scientist", und: "Researcher", cat: "Jobs & Professions" },
  { civ: "Biologist", und: "Chemist", cat: "Jobs & Professions" },
  { civ: "Physicist", und: "Mathematician", cat: "Jobs & Professions" },
  { civ: "Psychologist", und: "Psychiatrist", cat: "Jobs & Professions" },
  { civ: "Therapist", und: "Counsellor", cat: "Jobs & Professions" },
  { civ: "Surgeon", und: "Consultant", cat: "Jobs & Professions" },
  { civ: "Dentist", und: "Orthodontist", cat: "Jobs & Professions" },
  { civ: "Optician", und: "Optometrist", cat: "Jobs & Professions" },
  { civ: "Pharmacist", und: "Dispenser", cat: "Jobs & Professions" },
  { civ: "Physiotherapist", und: "Chiropractor", cat: "Jobs & Professions" },
  { civ: "Paramedic", und: "First Aider", cat: "Jobs & Professions" },
  { civ: "Midwife", und: "Health Visitor", cat: "Jobs & Professions" },
  { civ: "Vet", und: "Zoologist", cat: "Jobs & Professions" },
  { civ: "Farmer", und: "Rancher", cat: "Jobs & Professions" },
  { civ: "Gardener", und: "Landscaper", cat: "Jobs & Professions" },
  { civ: "Florist", und: "Horticulturist", cat: "Jobs & Professions" },
  { civ: "Builder", und: "Contractor", cat: "Jobs & Professions" },
  { civ: "Plumber", und: "Electrician", cat: "Jobs & Professions" },
  { civ: "Carpenter", und: "Joiner", cat: "Jobs & Professions" },
  { civ: "Bricklayer", und: "Mason", cat: "Jobs & Professions" },
  { civ: "Plasterer", und: "Tiler", cat: "Jobs & Professions" },
  { civ: "Decorator", und: "Painter", cat: "Jobs & Professions" },
  { civ: "Mechanic", und: "Technician", cat: "Jobs & Professions" },
  { civ: "Pilot", und: "Co-Pilot", cat: "Jobs & Professions" },
  { civ: "Flight Attendant", und: "Cabin Crew", cat: "Jobs & Professions" },
  { civ: "Captain", und: "First Mate", cat: "Jobs & Professions" },
  { civ: "Train Driver", und: "Bus Driver", cat: "Jobs & Professions" },
  { civ: "Taxi Driver", und: "Chauffeur", cat: "Jobs & Professions" },
  { civ: "Lorry Driver", und: "Delivery Driver", cat: "Jobs & Professions" },
  { civ: "Journalist", und: "Reporter", cat: "Jobs & Professions" },
  { civ: "Editor", und: "Publisher", cat: "Jobs & Professions" },
  { civ: "Author", und: "Novelist", cat: "Jobs & Professions" },
  { civ: "Poet", und: "Playwright", cat: "Jobs & Professions" },
  { civ: "Actor", und: "Actress", cat: "Jobs & Professions" },
  { civ: "Singer", und: "Vocalist", cat: "Jobs & Professions" },
  { civ: "Musician", und: "Composer", cat: "Jobs & Professions" },
  { civ: "Conductor", und: "Maestro", cat: "Jobs & Professions" },
  { civ: "Dancer", und: "Choreographer", cat: "Jobs & Professions" },
  { civ: "Artist", und: "Illustrator", cat: "Jobs & Professions" },
  { civ: "Sculptor", und: "Potter", cat: "Jobs & Professions" },
  { civ: "Photographer", und: "Cinematographer", cat: "Jobs & Professions" },
  { civ: "Model", und: "Influencer", cat: "Jobs & Professions" },
  { civ: "Fashion Designer", und: "Stylist", cat: "Jobs & Professions" },
  { civ: "Tailor", und: "Seamstress", cat: "Jobs & Professions" },
  { civ: "Hairdresser", und: "Barber", cat: "Jobs & Professions" },
  { civ: "Beautician", und: "Make-Up Artist", cat: "Jobs & Professions" },
  { civ: "Personal Trainer", und: "Sports Coach", cat: "Jobs & Professions" },
  { civ: "Athlete", und: "Sportsperson", cat: "Jobs & Professions" },
  { civ: "Police Officer", und: "Detective", cat: "Jobs & Professions" },
  { civ: "Firefighter", und: "Rescue Worker", cat: "Jobs & Professions" },
  { civ: "Soldier", und: "Marine", cat: "Jobs & Professions" },
  { civ: "Sailor", und: "Naval Officer", cat: "Jobs & Professions" },
  { civ: "Security Guard", und: "Bouncer", cat: "Jobs & Professions" },
  { civ: "Prison Officer", und: "Probation Officer", cat: "Jobs & Professions" },
  { civ: "Social Worker", und: "Care Worker", cat: "Jobs & Professions" },
  { civ: "Charity Worker", und: "Volunteer", cat: "Jobs & Professions" },
  { civ: "Receptionist", und: "Secretary", cat: "Jobs & Professions" },
  { civ: "Personal Assistant", und: "Administrator", cat: "Jobs & Professions" },
  { civ: "Salesperson", und: "Sales Rep", cat: "Jobs & Professions" },
  { civ: "Estate Agent", und: "Letting Agent", cat: "Jobs & Professions" },
  { civ: "Banker", und: "Financial Adviser", cat: "Jobs & Professions" },
  { civ: "Stockbroker", und: "Trader", cat: "Jobs & Professions" },
  { civ: "Actuary", und: "Underwriter", cat: "Jobs & Professions" },
  { civ: "Waiter", und: "Waitress", cat: "Jobs & Professions" },
  { civ: "Bartender", und: "Barista", cat: "Jobs & Professions" },
  { civ: "Cleaner", und: "Housekeeper", cat: "Jobs & Professions" },
  { civ: "Nanny", und: "Au Pair", cat: "Jobs & Professions" },
  { civ: "Librarian", und: "Archivist", cat: "Jobs & Professions" },
  { civ: "Curator", und: "Museum Guide", cat: "Jobs & Professions" },

  // ============================================
  // TRAVEL & ACCOMMODATION (60 pairs)
  // ============================================
  { civ: "Hotel", und: "Motel", cat: "Travel & Accommodation" },
  { civ: "Hostel", und: "Guest House", cat: "Travel & Accommodation" },
  { civ: "B&B", und: "Inn", cat: "Travel & Accommodation" },
  { civ: "Resort", und: "Spa", cat: "Travel & Accommodation" },
  { civ: "Villa", und: "Cottage", cat: "Travel & Accommodation" },
  { civ: "Apartment", und: "Flat", cat: "Travel & Accommodation" },
  { civ: "Penthouse", und: "Loft", cat: "Travel & Accommodation" },
  { civ: "Cabin", und: "Lodge", cat: "Travel & Accommodation" },
  { civ: "Chalet", und: "Bungalow", cat: "Travel & Accommodation" },
  { civ: "Tent", und: "Yurt", cat: "Travel & Accommodation" },
  { civ: "Caravan", und: "Campervan", cat: "Travel & Accommodation" },
  { civ: "Houseboat", und: "Narrowboat", cat: "Travel & Accommodation" },
  { civ: "Treehouse", und: "Glamping Pod", cat: "Travel & Accommodation" },
  { civ: "Castle", und: "Manor House", cat: "Travel & Accommodation" },
  { civ: "Suite", und: "Room", cat: "Travel & Accommodation" },
  { civ: "Single Room", und: "Double Room", cat: "Travel & Accommodation" },
  { civ: "Twin Room", und: "Family Room", cat: "Travel & Accommodation" },
  { civ: "En Suite", und: "Shared Bathroom", cat: "Travel & Accommodation" },
  { civ: "Breakfast Included", und: "Self-Catering", cat: "Travel & Accommodation" },
  { civ: "All-Inclusive", und: "Half Board", cat: "Travel & Accommodation" },
  { civ: "Full Board", und: "Room Only", cat: "Travel & Accommodation" },
  { civ: "Reception", und: "Lobby", cat: "Travel & Accommodation" },
  { civ: "Concierge", und: "Porter", cat: "Travel & Accommodation" },
  { civ: "Room Service", und: "Mini Bar", cat: "Travel & Accommodation" },
  { civ: "Check-In", und: "Check-Out", cat: "Travel & Accommodation" },
  { civ: "Reservation", und: "Booking", cat: "Travel & Accommodation" },
  { civ: "Vacancy", und: "No Vacancy", cat: "Travel & Accommodation" },
  { civ: "Tourist", und: "Traveller", cat: "Travel & Accommodation" },
  { civ: "Backpacker", und: "Gap Year Student", cat: "Travel & Accommodation" },
  { civ: "Package Holiday", und: "Independent Travel", cat: "Travel & Accommodation" },
  { civ: "City Break", und: "Weekend Getaway", cat: "Travel & Accommodation" },
  { civ: "Beach Holiday", und: "Ski Trip", cat: "Travel & Accommodation" },
  { civ: "Safari", und: "Expedition", cat: "Travel & Accommodation" },
  { civ: "Cruise", und: "Road Trip", cat: "Travel & Accommodation" },
  { civ: "Pilgrimage", und: "Retreat", cat: "Travel & Accommodation" },
  { civ: "Staycation", und: "Daycation", cat: "Travel & Accommodation" },
  { civ: "Layover", und: "Stopover", cat: "Travel & Accommodation" },
  { civ: "Itinerary", und: "Schedule", cat: "Travel & Accommodation" },
  { civ: "Guidebook", und: "Map", cat: "Travel & Accommodation" },
  { civ: "Phrasebook", und: "Translation App", cat: "Travel & Accommodation" },
  { civ: "Travel Insurance", und: "Health Insurance", cat: "Travel & Accommodation" },
  { civ: "Currency Exchange", und: "ATM", cat: "Travel & Accommodation" },
  { civ: "Duty Free", und: "Tax Free", cat: "Travel & Accommodation" },
  { civ: "Souvenir", und: "Memento", cat: "Travel & Accommodation" },
  { civ: "Postcard", und: "Photograph", cat: "Travel & Accommodation" },
  { civ: "Landmark", und: "Monument", cat: "Travel & Accommodation" },
  { civ: "Tourist Attraction", und: "Hidden Gem", cat: "Travel & Accommodation" },
  { civ: "Theme Park", und: "Amusement Park", cat: "Travel & Accommodation" },
  { civ: "Water Park", und: "Adventure Park", cat: "Travel & Accommodation" },
  { civ: "Museum", und: "Gallery", cat: "Travel & Accommodation" },
  { civ: "Castle", und: "Palace", cat: "Travel & Accommodation" },
  { civ: "Cathedral", und: "Church", cat: "Travel & Accommodation" },
  { civ: "Temple", und: "Shrine", cat: "Travel & Accommodation" },
  { civ: "Ruins", und: "Archaeological Site", cat: "Travel & Accommodation" },
  { civ: "Tower", und: "Observation Deck", cat: "Travel & Accommodation" },
  { civ: "Viewpoint", und: "Lookout", cat: "Travel & Accommodation" },
  { civ: "Guided Tour", und: "Self-Guided Tour", cat: "Travel & Accommodation" },
  { civ: "Walking Tour", und: "Bus Tour", cat: "Travel & Accommodation" },
  { civ: "Boat Trip", und: "Day Trip", cat: "Travel & Accommodation" },
  { civ: "Excursion", und: "Activity", cat: "Travel & Accommodation" },

  // ============================================
  // ACTIONS & EXPRESSIONS (80 pairs)
  // ============================================
  { civ: "Whisper", und: "Murmur", cat: "Actions & Expressions" },
  { civ: "Smile", und: "Grin", cat: "Actions & Expressions" },
  { civ: "Laugh", und: "Giggle", cat: "Actions & Expressions" },
  { civ: "Chuckle", und: "Snicker", cat: "Actions & Expressions" },
  { civ: "Cry", und: "Weep", cat: "Actions & Expressions" },
  { civ: "Sob", und: "Wail", cat: "Actions & Expressions" },
  { civ: "Shout", und: "Yell", cat: "Actions & Expressions" },
  { civ: "Scream", und: "Shriek", cat: "Actions & Expressions" },
  { civ: "Talk", und: "Chat", cat: "Actions & Expressions" },
  { civ: "Speak", und: "Say", cat: "Actions & Expressions" },
  { civ: "Tell", und: "Inform", cat: "Actions & Expressions" },
  { civ: "Ask", und: "Question", cat: "Actions & Expressions" },
  { civ: "Answer", und: "Reply", cat: "Actions & Expressions" },
  { civ: "Explain", und: "Describe", cat: "Actions & Expressions" },
  { civ: "Argue", und: "Debate", cat: "Actions & Expressions" },
  { civ: "Agree", und: "Concur", cat: "Actions & Expressions" },
  { civ: "Disagree", und: "Object", cat: "Actions & Expressions" },
  { civ: "Nod", und: "Shake Head", cat: "Actions & Expressions" },
  { civ: "Wave", und: "Beckon", cat: "Actions & Expressions" },
  { civ: "Point", und: "Gesture", cat: "Actions & Expressions" },
  { civ: "Clap", und: "Applaud", cat: "Actions & Expressions" },
  { civ: "Hug", und: "Embrace", cat: "Actions & Expressions" },
  { civ: "Kiss", und: "Peck", cat: "Actions & Expressions" },
  { civ: "Shake Hands", und: "High Five", cat: "Actions & Expressions" },
  { civ: "Fist Bump", und: "Elbow Bump", cat: "Actions & Expressions" },
  { civ: "Walk", und: "Stroll", cat: "Actions & Expressions" },
  { civ: "Run", und: "Sprint", cat: "Actions & Expressions" },
  { civ: "Jog", und: "Trot", cat: "Actions & Expressions" },
  { civ: "Skip", und: "Hop", cat: "Actions & Expressions" },
  { civ: "Jump", und: "Leap", cat: "Actions & Expressions" },
  { civ: "Climb", und: "Ascend", cat: "Actions & Expressions" },
  { civ: "Crawl", und: "Creep", cat: "Actions & Expressions" },
  { civ: "Slide", und: "Glide", cat: "Actions & Expressions" },
  { civ: "Dance", und: "Sway", cat: "Actions & Expressions" },
  { civ: "Spin", und: "Twirl", cat: "Actions & Expressions" },
  { civ: "Stretch", und: "Reach", cat: "Actions & Expressions" },
  { civ: "Bend", und: "Crouch", cat: "Actions & Expressions" },
  { civ: "Kneel", und: "Squat", cat: "Actions & Expressions" },
  { civ: "Sit", und: "Perch", cat: "Actions & Expressions" },
  { civ: "Stand", und: "Rise", cat: "Actions & Expressions" },
  { civ: "Lie Down", und: "Recline", cat: "Actions & Expressions" },
  { civ: "Sleep", und: "Nap", cat: "Actions & Expressions" },
  { civ: "Doze", und: "Slumber", cat: "Actions & Expressions" },
  { civ: "Wake", und: "Rouse", cat: "Actions & Expressions" },
  { civ: "Yawn", und: "Stretch", cat: "Actions & Expressions" },
  { civ: "Sneeze", und: "Cough", cat: "Actions & Expressions" },
  { civ: "Hiccup", und: "Burp", cat: "Actions & Expressions" },
  { civ: "Sigh", und: "Gasp", cat: "Actions & Expressions" },
  { civ: "Breathe", und: "Inhale", cat: "Actions & Expressions" },
  { civ: "Exhale", und: "Puff", cat: "Actions & Expressions" },
  { civ: "Blink", und: "Wink", cat: "Actions & Expressions" },
  { civ: "Stare", und: "Gaze", cat: "Actions & Expressions" },
  { civ: "Glance", und: "Peek", cat: "Actions & Expressions" },
  { civ: "Look", und: "Watch", cat: "Actions & Expressions" },
  { civ: "See", und: "Observe", cat: "Actions & Expressions" },
  { civ: "Listen", und: "Hear", cat: "Actions & Expressions" },
  { civ: "Smell", und: "Sniff", cat: "Actions & Expressions" },
  { civ: "Taste", und: "Savour", cat: "Actions & Expressions" },
  { civ: "Touch", und: "Feel", cat: "Actions & Expressions" },
  { civ: "Grab", und: "Grasp", cat: "Actions & Expressions" },
  { civ: "Hold", und: "Grip", cat: "Actions & Expressions" },
  { civ: "Carry", und: "Lift", cat: "Actions & Expressions" },
  { civ: "Drop", und: "Release", cat: "Actions & Expressions" },
  { civ: "Throw", und: "Toss", cat: "Actions & Expressions" },
  { civ: "Catch", und: "Grab", cat: "Actions & Expressions" },
  { civ: "Push", und: "Shove", cat: "Actions & Expressions" },
  { civ: "Pull", und: "Tug", cat: "Actions & Expressions" },
  { civ: "Drag", und: "Haul", cat: "Actions & Expressions" },
  { civ: "Hit", und: "Strike", cat: "Actions & Expressions" },
  { civ: "Kick", und: "Stomp", cat: "Actions & Expressions" },
  { civ: "Punch", und: "Slap", cat: "Actions & Expressions" },
  { civ: "Pinch", und: "Poke", cat: "Actions & Expressions" },
  { civ: "Scratch", und: "Rub", cat: "Actions & Expressions" },
  { civ: "Pat", und: "Stroke", cat: "Actions & Expressions" },
  { civ: "Tap", und: "Knock", cat: "Actions & Expressions" },
  { civ: "Write", und: "Type", cat: "Actions & Expressions" },
  { civ: "Read", und: "Scan", cat: "Actions & Expressions" },
  { civ: "Draw", und: "Sketch", cat: "Actions & Expressions" },
  { civ: "Paint", und: "Colour", cat: "Actions & Expressions" },
  { civ: "Think", und: "Ponder", cat: "Actions & Expressions" },

  // ============================================
  // EMOTIONS & FEELINGS (60 pairs)
  // ============================================
  { civ: "Happy", und: "Joyful", cat: "Emotions & Feelings" },
  { civ: "Sad", und: "Melancholy", cat: "Emotions & Feelings" },
  { civ: "Angry", und: "Furious", cat: "Emotions & Feelings" },
  { civ: "Annoyed", und: "Irritated", cat: "Emotions & Feelings" },
  { civ: "Frustrated", und: "Exasperated", cat: "Emotions & Feelings" },
  { civ: "Scared", und: "Frightened", cat: "Emotions & Feelings" },
  { civ: "Terrified", und: "Petrified", cat: "Emotions & Feelings" },
  { civ: "Nervous", und: "Anxious", cat: "Emotions & Feelings" },
  { civ: "Worried", und: "Concerned", cat: "Emotions & Feelings" },
  { civ: "Stressed", und: "Overwhelmed", cat: "Emotions & Feelings" },
  { civ: "Calm", und: "Peaceful", cat: "Emotions & Feelings" },
  { civ: "Relaxed", und: "Serene", cat: "Emotions & Feelings" },
  { civ: "Excited", und: "Thrilled", cat: "Emotions & Feelings" },
  { civ: "Enthusiastic", und: "Eager", cat: "Emotions & Feelings" },
  { civ: "Curious", und: "Intrigued", cat: "Emotions & Feelings" },
  { civ: "Surprised", und: "Astonished", cat: "Emotions & Feelings" },
  { civ: "Shocked", und: "Stunned", cat: "Emotions & Feelings" },
  { civ: "Confused", und: "Bewildered", cat: "Emotions & Feelings" },
  { civ: "Puzzled", und: "Perplexed", cat: "Emotions & Feelings" },
  { civ: "Bored", und: "Uninterested", cat: "Emotions & Feelings" },
  { civ: "Tired", und: "Exhausted", cat: "Emotions & Feelings" },
  { civ: "Sleepy", und: "Drowsy", cat: "Emotions & Feelings" },
  { civ: "Energetic", und: "Lively", cat: "Emotions & Feelings" },
  { civ: "Confident", und: "Self-Assured", cat: "Emotions & Feelings" },
  { civ: "Proud", und: "Satisfied", cat: "Emotions & Feelings" },
  { civ: "Grateful", und: "Thankful", cat: "Emotions & Feelings" },
  { civ: "Hopeful", und: "Optimistic", cat: "Emotions & Feelings" },
  { civ: "Disappointed", und: "Let Down", cat: "Emotions & Feelings" },
  { civ: "Embarrassed", und: "Ashamed", cat: "Emotions & Feelings" },
  { civ: "Guilty", und: "Remorseful", cat: "Emotions & Feelings" },
  { civ: "Jealous", und: "Envious", cat: "Emotions & Feelings" },
  { civ: "Lonely", und: "Isolated", cat: "Emotions & Feelings" },
  { civ: "Nostalgic", und: "Wistful", cat: "Emotions & Feelings" },
  { civ: "Content", und: "Fulfilled", cat: "Emotions & Feelings" },
  { civ: "Amused", und: "Entertained", cat: "Emotions & Feelings" },
  { civ: "Delighted", und: "Overjoyed", cat: "Emotions & Feelings" },
  { civ: "Loving", und: "Affectionate", cat: "Emotions & Feelings" },
  { civ: "Caring", und: "Compassionate", cat: "Emotions & Feelings" },
  { civ: "Sympathetic", und: "Empathetic", cat: "Emotions & Feelings" },
  { civ: "Inspired", und: "Motivated", cat: "Emotions & Feelings" },
  { civ: "Determined", und: "Resolute", cat: "Emotions & Feelings" },
  { civ: "Stubborn", und: "Obstinate", cat: "Emotions & Feelings" },
  { civ: "Patient", und: "Tolerant", cat: "Emotions & Feelings" },
  { civ: "Impatient", und: "Restless", cat: "Emotions & Feelings" },
  { civ: "Shy", und: "Timid", cat: "Emotions & Feelings" },
  { civ: "Bold", und: "Brave", cat: "Emotions & Feelings" },
  { civ: "Courageous", und: "Fearless", cat: "Emotions & Feelings" },
  { civ: "Cautious", und: "Wary", cat: "Emotions & Feelings" },
  { civ: "Suspicious", und: "Distrustful", cat: "Emotions & Feelings" },
  { civ: "Trusting", und: "Naive", cat: "Emotions & Feelings" },
  { civ: "Cynical", und: "Sceptical", cat: "Emotions & Feelings" },
  { civ: "Romantic", und: "Sentimental", cat: "Emotions & Feelings" },
  { civ: "Passionate", und: "Intense", cat: "Emotions & Feelings" },
  { civ: "Indifferent", und: "Apathetic", cat: "Emotions & Feelings" },
  { civ: "Bitter", und: "Resentful", cat: "Emotions & Feelings" },
  { civ: "Hurt", und: "Wounded", cat: "Emotions & Feelings" },
  { civ: "Offended", und: "Insulted", cat: "Emotions & Feelings" },
  { civ: "Relieved", und: "Reassured", cat: "Emotions & Feelings" },
  { civ: "Comfortable", und: "At Ease", cat: "Emotions & Feelings" },
  { civ: "Uncomfortable", und: "Uneasy", cat: "Emotions & Feelings" },

  // ============================================
  // TIME & SEASONS (50 pairs)
  // ============================================
  { civ: "Spring", und: "Summer", cat: "Time & Seasons" },
  { civ: "Autumn", und: "Winter", cat: "Time & Seasons" },
  { civ: "Morning", und: "Afternoon", cat: "Time & Seasons" },
  { civ: "Evening", und: "Night", cat: "Time & Seasons" },
  { civ: "Dawn", und: "Dusk", cat: "Time & Seasons" },
  { civ: "Midnight", und: "Midday", cat: "Time & Seasons" },
  { civ: "Sunrise", und: "Sunset", cat: "Time & Seasons" },
  { civ: "Today", und: "Tomorrow", cat: "Time & Seasons" },
  { civ: "Yesterday", und: "Last Week", cat: "Time & Seasons" },
  { civ: "Weekday", und: "Weekend", cat: "Time & Seasons" },
  { civ: "Monday", und: "Tuesday", cat: "Time & Seasons" },
  { civ: "Wednesday", und: "Thursday", cat: "Time & Seasons" },
  { civ: "Friday", und: "Saturday", cat: "Time & Seasons" },
  { civ: "January", und: "February", cat: "Time & Seasons" },
  { civ: "March", und: "April", cat: "Time & Seasons" },
  { civ: "May", und: "June", cat: "Time & Seasons" },
  { civ: "July", und: "August", cat: "Time & Seasons" },
  { civ: "September", und: "October", cat: "Time & Seasons" },
  { civ: "November", und: "December", cat: "Time & Seasons" },
  { civ: "Second", und: "Minute", cat: "Time & Seasons" },
  { civ: "Hour", und: "Day", cat: "Time & Seasons" },
  { civ: "Week", und: "Fortnight", cat: "Time & Seasons" },
  { civ: "Month", und: "Quarter", cat: "Time & Seasons" },
  { civ: "Year", und: "Decade", cat: "Time & Seasons" },
  { civ: "Century", und: "Millennium", cat: "Time & Seasons" },
  { civ: "Past", und: "Present", cat: "Time & Seasons" },
  { civ: "Future", und: "Now", cat: "Time & Seasons" },
  { civ: "Ancient", und: "Medieval", cat: "Time & Seasons" },
  { civ: "Modern", und: "Contemporary", cat: "Time & Seasons" },
  { civ: "Vintage", und: "Antique", cat: "Time & Seasons" },
  { civ: "Early", und: "Late", cat: "Time & Seasons" },
  { civ: "Soon", und: "Later", cat: "Time & Seasons" },
  { civ: "Always", und: "Never", cat: "Time & Seasons" },
  { civ: "Sometimes", und: "Often", cat: "Time & Seasons" },
  { civ: "Rarely", und: "Frequently", cat: "Time & Seasons" },
  { civ: "Permanent", und: "Temporary", cat: "Time & Seasons" },
  { civ: "Brief", und: "Lengthy", cat: "Time & Seasons" },
  { civ: "Quick", und: "Slow", cat: "Time & Seasons" },
  { civ: "Sudden", und: "Gradual", cat: "Time & Seasons" },
  { civ: "Instant", und: "Delayed", cat: "Time & Seasons" },
  { civ: "Deadline", und: "Due Date", cat: "Time & Seasons" },
  { civ: "Schedule", und: "Timetable", cat: "Time & Seasons" },
  { civ: "Calendar", und: "Diary", cat: "Time & Seasons" },
  { civ: "Appointment", und: "Meeting", cat: "Time & Seasons" },
  { civ: "Anniversary", und: "Birthday", cat: "Time & Seasons" },
  { civ: "Holiday", und: "Vacation", cat: "Time & Seasons" },
  { civ: "Bank Holiday", und: "Public Holiday", cat: "Time & Seasons" },
  { civ: "Long Weekend", und: "Short Break", cat: "Time & Seasons" },
  { civ: "Term", und: "Semester", cat: "Time & Seasons" },
  { civ: "Shift", und: "Rota", cat: "Time & Seasons" },

  // ============================================
  // CELEBRATIONS & EVENTS (50 pairs)
  // ============================================
  { civ: "Birthday", und: "Name Day", cat: "Celebrations & Events" },
  { civ: "Wedding", und: "Engagement", cat: "Celebrations & Events" },
  { civ: "Anniversary", und: "Jubilee", cat: "Celebrations & Events" },
  { civ: "Graduation", und: "Convocation", cat: "Celebrations & Events" },
  { civ: "Retirement", und: "Farewell", cat: "Celebrations & Events" },
  { civ: "Baby Shower", und: "Gender Reveal", cat: "Celebrations & Events" },
  { civ: "Christening", und: "Baptism", cat: "Celebrations & Events" },
  { civ: "Funeral", und: "Memorial", cat: "Celebrations & Events" },
  { civ: "Christmas", und: "New Year", cat: "Celebrations & Events" },
  { civ: "Easter", und: "Good Friday", cat: "Celebrations & Events" },
  { civ: "Halloween", und: "Bonfire Night", cat: "Celebrations & Events" },
  { civ: "Valentine's Day", und: "Mother's Day", cat: "Celebrations & Events" },
  { civ: "Father's Day", und: "Grandparents' Day", cat: "Celebrations & Events" },
  { civ: "Thanksgiving", und: "Harvest Festival", cat: "Celebrations & Events" },
  { civ: "Diwali", und: "Hanukkah", cat: "Celebrations & Events" },
  { civ: "Eid", und: "Ramadan", cat: "Celebrations & Events" },
  { civ: "Chinese New Year", und: "Lunar New Year", cat: "Celebrations & Events" },
  { civ: "St Patrick's Day", und: "St George's Day", cat: "Celebrations & Events" },
  { civ: "Party", und: "Gathering", cat: "Celebrations & Events" },
  { civ: "Reception", und: "Banquet", cat: "Celebrations & Events" },
  { civ: "Dinner Party", und: "Cocktail Party", cat: "Celebrations & Events" },
  { civ: "Barbecue", und: "Picnic", cat: "Celebrations & Events" },
  { civ: "House Warming", und: "Open House", cat: "Celebrations & Events" },
  { civ: "Reunion", und: "Get-Together", cat: "Celebrations & Events" },
  { civ: "Stag Do", und: "Hen Party", cat: "Celebrations & Events" },
  { civ: "Prom", und: "School Disco", cat: "Celebrations & Events" },
  { civ: "Gala", und: "Ball", cat: "Celebrations & Events" },
  { civ: "Carnival", und: "Parade", cat: "Celebrations & Events" },
  { civ: "Festival", und: "Fair", cat: "Celebrations & Events" },
  { civ: "Concert", und: "Gig", cat: "Celebrations & Events" },
  { civ: "Show", und: "Performance", cat: "Celebrations & Events" },
  { civ: "Exhibition", und: "Display", cat: "Celebrations & Events" },
  { civ: "Opening Night", und: "Premiere", cat: "Celebrations & Events" },
  { civ: "Launch", und: "Unveiling", cat: "Celebrations & Events" },
  { civ: "Award Ceremony", und: "Prize Giving", cat: "Celebrations & Events" },
  { civ: "Conference", und: "Symposium", cat: "Celebrations & Events" },
  { civ: "Seminar", und: "Workshop", cat: "Celebrations & Events" },
  { civ: "Lecture", und: "Presentation", cat: "Celebrations & Events" },
  { civ: "Webinar", und: "Online Event", cat: "Celebrations & Events" },
  { civ: "Ceremony", und: "Ritual", cat: "Celebrations & Events" },
  { civ: "Service", und: "Mass", cat: "Celebrations & Events" },
  { civ: "Vigil", und: "Procession", cat: "Celebrations & Events" },
  { civ: "Coronation", und: "Inauguration", cat: "Celebrations & Events" },
  { civ: "State Dinner", und: "Royal Wedding", cat: "Celebrations & Events" },
  { civ: "Sports Day", und: "Prize Day", cat: "Celebrations & Events" },
  { civ: "Open Day", und: "Careers Fair", cat: "Celebrations & Events" },
  { civ: "Fundraiser", und: "Charity Event", cat: "Celebrations & Events" },
  { civ: "Raffle", und: "Tombola", cat: "Celebrations & Events" },
  { civ: "Auction", und: "Sale", cat: "Celebrations & Events" },
  { civ: "Fete", und: "Garden Party", cat: "Celebrations & Events" },

  // ============================================
  // RELATIONSHIPS & PEOPLE (50 pairs)
  // ============================================
  { civ: "Friend", und: "Acquaintance", cat: "Relationships & People" },
  { civ: "Best Friend", und: "Close Friend", cat: "Relationships & People" },
  { civ: "Colleague", und: "Co-Worker", cat: "Relationships & People" },
  { civ: "Boss", und: "Manager", cat: "Relationships & People" },
  { civ: "Employee", und: "Staff Member", cat: "Relationships & People" },
  { civ: "Partner", und: "Spouse", cat: "Relationships & People" },
  { civ: "Husband", und: "Wife", cat: "Relationships & People" },
  { civ: "Boyfriend", und: "Girlfriend", cat: "Relationships & People" },
  { civ: "Fiancé", und: "Fiancée", cat: "Relationships & People" },
  { civ: "Ex", und: "Former Partner", cat: "Relationships & People" },
  { civ: "Mother", und: "Father", cat: "Relationships & People" },
  { civ: "Mum", und: "Dad", cat: "Relationships & People" },
  { civ: "Son", und: "Daughter", cat: "Relationships & People" },
  { civ: "Brother", und: "Sister", cat: "Relationships & People" },
  { civ: "Sibling", und: "Twin", cat: "Relationships & People" },
  { civ: "Grandmother", und: "Grandfather", cat: "Relationships & People" },
  { civ: "Grandma", und: "Grandad", cat: "Relationships & People" },
  { civ: "Grandson", und: "Granddaughter", cat: "Relationships & People" },
  { civ: "Aunt", und: "Uncle", cat: "Relationships & People" },
  { civ: "Nephew", und: "Niece", cat: "Relationships & People" },
  { civ: "Cousin", und: "Second Cousin", cat: "Relationships & People" },
  { civ: "In-Law", und: "Step-Parent", cat: "Relationships & People" },
  { civ: "Mother-in-Law", und: "Father-in-Law", cat: "Relationships & People" },
  { civ: "Stepmother", und: "Stepfather", cat: "Relationships & People" },
  { civ: "Half-Brother", und: "Half-Sister", cat: "Relationships & People" },
  { civ: "Godmother", und: "Godfather", cat: "Relationships & People" },
  { civ: "Guardian", und: "Foster Parent", cat: "Relationships & People" },
  { civ: "Babysitter", und: "Childminder", cat: "Relationships & People" },
  { civ: "Neighbour", und: "Flatmate", cat: "Relationships & People" },
  { civ: "Roommate", und: "Housemate", cat: "Relationships & People" },
  { civ: "Landlord", und: "Tenant", cat: "Relationships & People" },
  { civ: "Guest", und: "Host", cat: "Relationships & People" },
  { civ: "Visitor", und: "Resident", cat: "Relationships & People" },
  { civ: "Stranger", und: "Passerby", cat: "Relationships & People" },
  { civ: "Customer", und: "Client", cat: "Relationships & People" },
  { civ: "Patient", und: "Carer", cat: "Relationships & People" },
  { civ: "Student", und: "Pupil", cat: "Relationships & People" },
  { civ: "Teacher", und: "Tutor", cat: "Relationships & People" },
  { civ: "Mentor", und: "Coach", cat: "Relationships & People" },
  { civ: "Apprentice", und: "Trainee", cat: "Relationships & People" },
  { civ: "Junior", und: "Senior", cat: "Relationships & People" },
  { civ: "Volunteer", und: "Intern", cat: "Relationships & People" },
  { civ: "Member", und: "Subscriber", cat: "Relationships & People" },
  { civ: "Follower", und: "Fan", cat: "Relationships & People" },
  { civ: "Supporter", und: "Ally", cat: "Relationships & People" },
  { civ: "Rival", und: "Competitor", cat: "Relationships & People" },
  { civ: "Enemy", und: "Opponent", cat: "Relationships & People" },
  { civ: "Stranger", und: "Unknown", cat: "Relationships & People" },
  { civ: "Witness", und: "Bystander", cat: "Relationships & People" },
  { civ: "Victim", und: "Survivor", cat: "Relationships & People" },

  // ============================================
  // BUILDINGS & ARCHITECTURE (50 pairs)
  // ============================================
  { civ: "House", und: "Flat", cat: "Buildings & Architecture" },
  { civ: "Bungalow", und: "Cottage", cat: "Buildings & Architecture" },
  { civ: "Mansion", und: "Manor", cat: "Buildings & Architecture" },
  { civ: "Terraced House", und: "Semi-Detached", cat: "Buildings & Architecture" },
  { civ: "Detached House", und: "Town House", cat: "Buildings & Architecture" },
  { civ: "Maisonette", und: "Duplex", cat: "Buildings & Architecture" },
  { civ: "Studio Flat", und: "Bedsit", cat: "Buildings & Architecture" },
  { civ: "Penthouse", und: "Loft Apartment", cat: "Buildings & Architecture" },
  { civ: "Office", und: "Workplace", cat: "Buildings & Architecture" },
  { civ: "Factory", und: "Warehouse", cat: "Buildings & Architecture" },
  { civ: "Shop", und: "Store", cat: "Buildings & Architecture" },
  { civ: "Supermarket", und: "Hypermarket", cat: "Buildings & Architecture" },
  { civ: "Shopping Centre", und: "Retail Park", cat: "Buildings & Architecture" },
  { civ: "Restaurant", und: "Café", cat: "Buildings & Architecture" },
  { civ: "Pub", und: "Bar", cat: "Buildings & Architecture" },
  { civ: "Nightclub", und: "Disco", cat: "Buildings & Architecture" },
  { civ: "Cinema", und: "Theatre", cat: "Buildings & Architecture" },
  { civ: "Library", und: "Archive", cat: "Buildings & Architecture" },
  { civ: "Museum", und: "Gallery", cat: "Buildings & Architecture" },
  { civ: "School", und: "College", cat: "Buildings & Architecture" },
  { civ: "University", und: "Academy", cat: "Buildings & Architecture" },
  { civ: "Hospital", und: "Clinic", cat: "Buildings & Architecture" },
  { civ: "Surgery", und: "Health Centre", cat: "Buildings & Architecture" },
  { civ: "Pharmacy", und: "Chemist", cat: "Buildings & Architecture" },
  { civ: "Bank", und: "Building Society", cat: "Buildings & Architecture" },
  { civ: "Post Office", und: "Sorting Office", cat: "Buildings & Architecture" },
  { civ: "Police Station", und: "Fire Station", cat: "Buildings & Architecture" },
  { civ: "Town Hall", und: "Council Offices", cat: "Buildings & Architecture" },
  { civ: "Court", und: "Tribunal", cat: "Buildings & Architecture" },
  { civ: "Prison", und: "Detention Centre", cat: "Buildings & Architecture" },
  { civ: "Church", und: "Chapel", cat: "Buildings & Architecture" },
  { civ: "Cathedral", und: "Basilica", cat: "Buildings & Architecture" },
  { civ: "Mosque", und: "Temple", cat: "Buildings & Architecture" },
  { civ: "Synagogue", und: "Gurdwara", cat: "Buildings & Architecture" },
  { civ: "Stadium", und: "Arena", cat: "Buildings & Architecture" },
  { civ: "Sports Hall", und: "Leisure Centre", cat: "Buildings & Architecture" },
  { civ: "Swimming Pool", und: "Lido", cat: "Buildings & Architecture" },
  { civ: "Gym", und: "Fitness Centre", cat: "Buildings & Architecture" },
  { civ: "Skyscraper", und: "Tower Block", cat: "Buildings & Architecture" },
  { civ: "High-Rise", und: "Low-Rise", cat: "Buildings & Architecture" },
  { civ: "Monument", und: "Memorial", cat: "Buildings & Architecture" },
  { civ: "Statue", und: "Sculpture", cat: "Buildings & Architecture" },
  { civ: "Fountain", und: "Water Feature", cat: "Buildings & Architecture" },
  { civ: "Arch", und: "Gateway", cat: "Buildings & Architecture" },
  { civ: "Tower", und: "Spire", cat: "Buildings & Architecture" },
  { civ: "Dome", und: "Cupola", cat: "Buildings & Architecture" },
  { civ: "Pillar", und: "Column", cat: "Buildings & Architecture" },
  { civ: "Balustrade", und: "Railing", cat: "Buildings & Architecture" },
  { civ: "Portico", und: "Porch", cat: "Buildings & Architecture" },
  { civ: "Courtyard", und: "Quadrangle", cat: "Buildings & Architecture" },

  // ============================================
  // EDUCATION & LEARNING (40 pairs)
  // ============================================
  { civ: "Primary School", und: "Secondary School", cat: "Education & Learning" },
  { civ: "Grammar School", und: "Comprehensive", cat: "Education & Learning" },
  { civ: "Private School", und: "State School", cat: "Education & Learning" },
  { civ: "Boarding School", und: "Day School", cat: "Education & Learning" },
  { civ: "Sixth Form", und: "College", cat: "Education & Learning" },
  { civ: "Undergraduate", und: "Postgraduate", cat: "Education & Learning" },
  { civ: "Bachelor's", und: "Master's", cat: "Education & Learning" },
  { civ: "PhD", und: "Doctorate", cat: "Education & Learning" },
  { civ: "Diploma", und: "Certificate", cat: "Education & Learning" },
  { civ: "Degree", und: "Qualification", cat: "Education & Learning" },
  { civ: "GCSE", und: "A-Level", cat: "Education & Learning" },
  { civ: "Exam", und: "Test", cat: "Education & Learning" },
  { civ: "Quiz", und: "Assessment", cat: "Education & Learning" },
  { civ: "Coursework", und: "Assignment", cat: "Education & Learning" },
  { civ: "Essay", und: "Dissertation", cat: "Education & Learning" },
  { civ: "Thesis", und: "Report", cat: "Education & Learning" },
  { civ: "Lecture", und: "Seminar", cat: "Education & Learning" },
  { civ: "Tutorial", und: "Workshop", cat: "Education & Learning" },
  { civ: "Class", und: "Lesson", cat: "Education & Learning" },
  { civ: "Subject", und: "Module", cat: "Education & Learning" },
  { civ: "Curriculum", und: "Syllabus", cat: "Education & Learning" },
  { civ: "Textbook", und: "Workbook", cat: "Education & Learning" },
  { civ: "Notebook", und: "Exercise Book", cat: "Education & Learning" },
  { civ: "Revision", und: "Homework", cat: "Education & Learning" },
  { civ: "Study", und: "Research", cat: "Education & Learning" },
  { civ: "Theory", und: "Practice", cat: "Education & Learning" },
  { civ: "Knowledge", und: "Skill", cat: "Education & Learning" },
  { civ: "Fact", und: "Opinion", cat: "Education & Learning" },
  { civ: "Question", und: "Answer", cat: "Education & Learning" },
  { civ: "Problem", und: "Solution", cat: "Education & Learning" },
  { civ: "Pass", und: "Fail", cat: "Education & Learning" },
  { civ: "Grade", und: "Mark", cat: "Education & Learning" },
  { civ: "First", und: "2:1", cat: "Education & Learning" },
  { civ: "Distinction", und: "Merit", cat: "Education & Learning" },
  { civ: "Scholarship", und: "Bursary", cat: "Education & Learning" },
  { civ: "Grant", und: "Loan", cat: "Education & Learning" },
  { civ: "Campus", und: "University Grounds", cat: "Education & Learning" },
  { civ: "Lecture Hall", und: "Classroom", cat: "Education & Learning" },
  { civ: "Laboratory", und: "Studio", cat: "Education & Learning" },
  { civ: "Library", und: "Study Room", cat: "Education & Learning" },

  // ============================================
  // HEALTH & BODY (50 pairs)
  // ============================================
  { civ: "Head", und: "Face", cat: "Health & Body" },
  { civ: "Forehead", und: "Temple", cat: "Health & Body" },
  { civ: "Eye", und: "Eyebrow", cat: "Health & Body" },
  { civ: "Nose", und: "Nostril", cat: "Health & Body" },
  { civ: "Mouth", und: "Lips", cat: "Health & Body" },
  { civ: "Teeth", und: "Tongue", cat: "Health & Body" },
  { civ: "Cheek", und: "Chin", cat: "Health & Body" },
  { civ: "Ear", und: "Earlobe", cat: "Health & Body" },
  { civ: "Neck", und: "Throat", cat: "Health & Body" },
  { civ: "Shoulder", und: "Back", cat: "Health & Body" },
  { civ: "Arm", und: "Elbow", cat: "Health & Body" },
  { civ: "Wrist", und: "Hand", cat: "Health & Body" },
  { civ: "Palm", und: "Fist", cat: "Health & Body" },
  { civ: "Finger", und: "Thumb", cat: "Health & Body" },
  { civ: "Nail", und: "Knuckle", cat: "Health & Body" },
  { civ: "Chest", und: "Stomach", cat: "Health & Body" },
  { civ: "Waist", und: "Hip", cat: "Health & Body" },
  { civ: "Leg", und: "Thigh", cat: "Health & Body" },
  { civ: "Knee", und: "Shin", cat: "Health & Body" },
  { civ: "Calf", und: "Ankle", cat: "Health & Body" },
  { civ: "Foot", und: "Heel", cat: "Health & Body" },
  { civ: "Toe", und: "Sole", cat: "Health & Body" },
  { civ: "Heart", und: "Lung", cat: "Health & Body" },
  { civ: "Brain", und: "Mind", cat: "Health & Body" },
  { civ: "Liver", und: "Kidney", cat: "Health & Body" },
  { civ: "Bone", und: "Muscle", cat: "Health & Body" },
  { civ: "Skin", und: "Hair", cat: "Health & Body" },
  { civ: "Blood", und: "Vein", cat: "Health & Body" },
  { civ: "Cold", und: "Flu", cat: "Health & Body" },
  { civ: "Cough", und: "Sore Throat", cat: "Health & Body" },
  { civ: "Headache", und: "Migraine", cat: "Health & Body" },
  { civ: "Fever", und: "Temperature", cat: "Health & Body" },
  { civ: "Rash", und: "Spots", cat: "Health & Body" },
  { civ: "Bruise", und: "Cut", cat: "Health & Body" },
  { civ: "Sprain", und: "Strain", cat: "Health & Body" },
  { civ: "Fracture", und: "Break", cat: "Health & Body" },
  { civ: "Allergy", und: "Intolerance", cat: "Health & Body" },
  { civ: "Infection", und: "Virus", cat: "Health & Body" },
  { civ: "Disease", und: "Illness", cat: "Health & Body" },
  { civ: "Symptom", und: "Sign", cat: "Health & Body" },
  { civ: "Diagnosis", und: "Prognosis", cat: "Health & Body" },
  { civ: "Treatment", und: "Therapy", cat: "Health & Body" },
  { civ: "Medicine", und: "Medication", cat: "Health & Body" },
  { civ: "Tablet", und: "Capsule", cat: "Health & Body" },
  { civ: "Prescription", und: "Over-the-Counter", cat: "Health & Body" },
  { civ: "Injection", und: "Vaccine", cat: "Health & Body" },
  { civ: "Surgery", und: "Operation", cat: "Health & Body" },
  { civ: "Check-Up", und: "Examination", cat: "Health & Body" },
  { civ: "X-Ray", und: "Scan", cat: "Health & Body" },
  { civ: "Blood Test", und: "Urine Test", cat: "Health & Body" },

  // ============================================
  // FRIENDS
  // ============================================
  { civ: "Cam", und: "Clam", cat: "Friends" },
  { civ: "Cam", und: "Ellio", cat: "Friends" },
  { civ: "Cam", und: "Dan", cat: "Friends" },
  { civ: "Cam", und: "Matt", cat: "Friends" },
  { civ: "Cam", und: "Frab", cat: "Friends" },
  { civ: "Cam", und: "Sam", cat: "Friends" },
  { civ: "Cam", und: "Max", cat: "Friends" },
  { civ: "Clam", und: "Ellio", cat: "Friends" },
  { civ: "Clam", und: "Dan", cat: "Friends" },
  { civ: "Clam", und: "Matt", cat: "Friends" },
  { civ: "Clam", und: "Frab", cat: "Friends" },
  { civ: "Clam", und: "Sam", cat: "Friends" },
  { civ: "Clam", und: "Max", cat: "Friends" },
  { civ: "Ellio", und: "Dan", cat: "Friends" },
  { civ: "Ellio", und: "Matt", cat: "Friends" },
  { civ: "Ellio", und: "Frab", cat: "Friends" },
  { civ: "Ellio", und: "Sam", cat: "Friends" },
  { civ: "Ellio", und: "Max", cat: "Friends" },
  { civ: "Dan", und: "Matt", cat: "Friends" },
  { civ: "Dan", und: "Frab", cat: "Friends" },
  { civ: "Dan", und: "Sam", cat: "Friends" },
  { civ: "Dan", und: "Max", cat: "Friends" },
  { civ: "Matt", und: "Frab", cat: "Friends" },
  { civ: "Matt", und: "Sam", cat: "Friends" },
  { civ: "Matt", und: "Max", cat: "Friends" },
  { civ: "Frab", und: "Sam", cat: "Friends" },
  { civ: "Frab", und: "Max", cat: "Friends" },
  { civ: "Sam", und: "Max", cat: "Friends" },
];

// Get all unique categories
function getCategories() {
  return [...new Set(wordPairs.map(p => p.cat))];
}

// Get random word pair (optionally filtered by category)
function getRandomWordPair(category = null) {
  let pairs = wordPairs;
  if (category) {
    pairs = wordPairs.filter(p => p.cat === category);
  }
  if (pairs.length === 0) {
    pairs = wordPairs; // Fallback to all if category empty
  }
  const index = Math.floor(Math.random() * pairs.length);
  return pairs[index];
}

// Get word pairs by category
function getWordPairsByCategory(category) {
  return wordPairs.filter(p => p.cat === category);
}

// Get count of pairs per category
function getCategoryCounts() {
  const counts = {};
  wordPairs.forEach(p => {
    counts[p.cat] = (counts[p.cat] || 0) + 1;
  });
  return counts;
}

// Get total number of word pairs
function getTotalPairs() {
  return wordPairs.length;
}

module.exports = { 
  wordPairs, 
  getCategories, 
  getRandomWordPair, 
  getWordPairsByCategory,
  getCategoryCounts,
  getTotalPairs
};